
== Solved Power System State Profiles

**IEC 61970-456:2021** belongs to the IEC 61970-450 to IEC 61970-499 series that, taken as a whole, defines at an abstract level the content and exchange mechanisms used for data transmitted between power system analyses applications, control centres and/or control centre components.

The purpose of this document is to rigorously define the subset of classes, class attributes, and roles from the CIM necessary to describe the result of state estimation, power flow and other similar applications that produce a steady-state solution of a power network, under a set of use cases which are included informatively in this document.

This document is intended for two distinct audiences, data producers and data recipients, and can be read from those two perspectives. From the standpoint of model export software used by a data producer, the document defines how a producer may describe an instance of a network case in order to make it available to some other program. From the standpoint of a consumer, the document defines what that importing software must be able to interpret in order to consume power flow cases.

There are many different use cases for which use of this document is expected and they differ in the way that the document will be applied in each case. Implementers are expected to consider what use cases they wish to cover in order to know the extent of different options they must cover. As an example, the profiles defined in this document will be used in some cases to exchange starting conditions rather than solved conditions, so if this is an important use case, it means that a consumer application needs to be able to handle an unsolved state as well as one which has met some solution criteria.

This third edition cancels and replaces the second edition published in 2018. This edition constitutes a technical revision. It is based on the IEC 61970 UML version ‘IEC61970CIM17v40’, dated 2020-08-24.

This edition includes the following significant technical changes with respect to the previous edition:  footnote:[This overview is taken from the public abstract for the https://webstore.iec.ch/en/publication/68054[IEC 61970-456:2021] I.S.]

a. Updated to support CIM17 (IEC 61970-301:2020+AMD1) and align with IEC 61970-452:ED4.
b. The classes PowerElectronicsConnection, PowerElectronicsUnit and PowerElectronicsWindUnit are added to the Steady State Hypothesis (SSH) profile to match the changes done for Edition 4 of IEC 61970-452 , Core Equipment profile.
c. Added relevant terms used in this document.
d. Clarified use of Equipment.inService and Equipment.normallyInService.
