:pdf-themesdir: {docdir}
:pdf-theme: adoc-inline-rdfs

== ShortCircuit Profile Specification

// Settings:
:doctype: inline
:reproducible:
:icons: font
:sectnums:

Profile namespace: http://iec.ch/TC57/ns/CIM/ShortCircuit-EU/3.0#

plantuml::./Profiles/CGMES-ShortCircuit.rdfs-t2b.puml[format=svg, align=center, caption="Figure 1: ", title="ShortCircuit Profile"]

== Profile Specification

This profile represents the equipment of the power system and their hierarchical relationships.


=== Concrete Classes

[#ACLineSegment]
==== (Description) ACLineSegment

Inheritance path = <<Conductor,Conductor>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A wire or combination of wires, with consistent electrical characteristics, building a single electrical system, used to carry alternating current between points in the power system.

For symmetrical, transposed three phase lines, it is sufficient to use attributes of the line segment, which describe impedances and admittances for the entire length of the segment. Additionally impedances can be computed by using length and associated per length impedances.

The BaseVoltage at the two ends of ACLineSegments in a Line shall have the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly different BaseVoltage.nominalVoltages and variation is allowed. Larger voltage difference in general requires use of an equivalent branch.




*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|b0ch
|1..1
|<<Susceptance,Susceptance>>
|
Zero sequence shunt (charging) susceptance, uniformly distributed, of the entire line section.


|g0ch
|1..1
|<<Conductance,Conductance>>
|
Zero sequence shunt (charging) conductance, uniformly distributed, of the entire line section.


|r0
|1..1
|<<Resistance,Resistance>>
|
Zero sequence series resistance of the entire line section.


|shortCircuitEndTemperature
|1..1
|<<Temperature,Temperature>>
|
Maximum permitted temperature at the end of SC for the calculation of minimum short-circuit currents. Used for short circuit data exchange according to IEC 60909.


|x0
|1..1
|<<Reactance,Reactance>>
|
Zero sequence series reactance of the entire line section.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AsynchronousMachine]
==== (Description) AsynchronousMachine

Inheritance path = <<RotatingMachine,RotatingMachine>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A rotating machine whose shaft rotates asynchronously with the electrical field. Also known as an induction machine with no external connection to the rotor windings, e.g. squirrel-cage induction machine.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|converterFedDrive
|1..1
|<<Boolean,Boolean>>
|
Indicates whether the machine is a converter fed drive. Used for short circuit data exchange according to IEC 60909.


|efficiency
|1..1
|<<PerCent,PerCent>>
|
Efficiency of the asynchronous machine at nominal operation as a percentage. Indicator for converter drive motors. Used for short circuit data exchange according to IEC 60909.


|iaIrRatio
|1..1
|<<Float,Float>>
|
Ratio of locked-rotor current to the rated current of the motor (Ia/Ir). Used for short circuit data exchange according to IEC 60909.


|polePairNumber
|1..1
|<<Integer,Integer>>
|
Number of pole pairs of stator. Used for short circuit data exchange according to IEC 60909.


|ratedMechanicalPower
|1..1
|<<ActivePower,ActivePower>>
|
Rated mechanical power (Pr in IEC 60909-0). Used for short circuit data exchange according to IEC 60909.


|reversible
|1..1
|<<Boolean,Boolean>>
|
Indicates for converter drive motors if the power can be reversible. Used for short circuit data exchange according to IEC 60909.


|rxLockedRotorRatio
|0..1
|<<Float,Float>>
|
Locked rotor ratio (R/X). Used for short circuit data exchange according to IEC 60909.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#BusbarSection]
==== (Description) BusbarSection

Inheritance path = <<Connector,Connector>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A conductor, or group of conductors, with negligible impedance, that serve to connect other conducting equipment within a single substation.

Voltage measurements are typically obtained from voltage transformers that are connected to busbar sections. A bus bar section may have many physical terminals but for analysis is modelled with exactly one logical terminal.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|ipMax
|0..1
|<<CurrentFlow,CurrentFlow>>
|
Maximum allowable peak short-circuit current of busbar (Ipmax in IEC 60909-0).

Mechanical limit of the busbar in the substation itself. Used for short circuit data exchange according to IEC 60909.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EnergySource]
==== (Description) EnergySource

Inheritance path = <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A generic equivalent for an energy supplier on a transmission or distribution voltage level.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|r
|0..1
|<<Resistance,Resistance>>
|
Positive sequence Thevenin resistance.


|r0
|0..1
|<<Resistance,Resistance>>
|
Zero sequence Thevenin resistance.


|rn
|0..1
|<<Resistance,Resistance>>
|
Negative sequence Thevenin resistance.


|x
|0..1
|<<Reactance,Reactance>>
|
Positive sequence Thevenin reactance.


|x0
|0..1
|<<Reactance,Reactance>>
|
Zero sequence Thevenin reactance.


|xn
|0..1
|<<Reactance,Reactance>>
|
Negative sequence Thevenin reactance.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EquivalentBranch]
==== (Description) EquivalentBranch

Inheritance path = <<EquivalentEquipment,EquivalentEquipment>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The class represents equivalent branches. In cases where a transformer phase shift is modelled and the EquivalentBranch is spanning the same nodes, the impedance quantities for the EquivalentBranch shall consider the needed phase shift.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|negativeR12
|1..1
|<<Resistance,Resistance>>
|
Negative sequence series resistance from terminal sequence 1 to terminal sequence 2. Used for short circuit data exchange according to IEC 60909.

EquivalentBranch is a result of network reduction prior to the data exchange.


|negativeR21
|1..1
|<<Resistance,Resistance>>
|
Negative sequence series resistance from terminal sequence 2 to terminal sequence 1. Used for short circuit data exchange according to IEC 60909.

EquivalentBranch is a result of network reduction prior to the data exchange.


|negativeX12
|1..1
|<<Reactance,Reactance>>
|
Negative sequence series reactance from terminal sequence 1 to terminal sequence 2. Used for short circuit data exchange according to IEC 60909.

Usage : EquivalentBranch is a result of network reduction prior to the data exchange.


|negativeX21
|1..1
|<<Reactance,Reactance>>
|
Negative sequence series reactance from terminal sequence 2 to terminal sequence 1. Used for short circuit data exchange according to IEC 60909.

Usage: EquivalentBranch is a result of network reduction prior to the data exchange.


|positiveR12
|1..1
|<<Resistance,Resistance>>
|
Positive sequence series resistance from terminal sequence 1 to terminal sequence 2 . Used for short circuit data exchange according to IEC 60909.

EquivalentBranch is a result of network reduction prior to the data exchange.


|positiveR21
|1..1
|<<Resistance,Resistance>>
|
Positive sequence series resistance from terminal sequence 2 to terminal sequence 1. Used for short circuit data exchange according to IEC 60909.

EquivalentBranch is a result of network reduction prior to the data exchange.


|positiveX12
|1..1
|<<Reactance,Reactance>>
|
Positive sequence series reactance from terminal sequence 1 to terminal sequence 2. Used for short circuit data exchange according to IEC 60909.

Usage : EquivalentBranch is a result of network reduction prior to the data exchange.


|positiveX21
|1..1
|<<Reactance,Reactance>>
|
Positive sequence series reactance from terminal sequence 2 to terminal sequence 1. Used for short circuit data exchange according to IEC 60909.

Usage : EquivalentBranch is a result of network reduction prior to the data exchange.


|zeroR12
|1..1
|<<Resistance,Resistance>>
|
Zero sequence series resistance from terminal sequence 1 to terminal sequence 2. Used for short circuit data exchange according to IEC 60909.

EquivalentBranch is a result of network reduction prior to the data exchange.


|zeroR21
|1..1
|<<Resistance,Resistance>>
|
Zero sequence series resistance from terminal sequence 2 to terminal sequence 1. Used for short circuit data exchange according to IEC 60909.

Usage : EquivalentBranch is a result of network reduction prior to the data exchange.


|zeroX12
|1..1
|<<Reactance,Reactance>>
|
Zero sequence series reactance from terminal sequence 1 to terminal sequence 2. Used for short circuit data exchange according to IEC 60909.

Usage : EquivalentBranch is a result of network reduction prior to the data exchange.


|zeroX21
|1..1
|<<Reactance,Reactance>>
|
Zero sequence series reactance from terminal sequence 2 to terminal sequence 1. Used for short circuit data exchange according to IEC 60909.

Usage : EquivalentBranch is a result of network reduction prior to the data exchange.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EquivalentInjection]
==== (Description) EquivalentInjection

Inheritance path = <<EquivalentEquipment,EquivalentEquipment>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

This class represents equivalent injections (generation or load). Voltage regulation is allowed only at the point of connection.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|r
|1..1
|<<Resistance,Resistance>>
|
Positive sequence resistance. Used to represent Extended-Ward (IEC 60909).

Usage : Extended-Ward is a result of network reduction prior to the data exchange.


|r0
|1..1
|<<Resistance,Resistance>>
|
Zero sequence resistance. Used to represent Extended-Ward (IEC 60909).

Usage : Extended-Ward is a result of network reduction prior to the data exchange.


|r2
|1..1
|<<Resistance,Resistance>>
|
Negative sequence resistance. Used to represent Extended-Ward (IEC 60909).

Usage : Extended-Ward is a result of network reduction prior to the data exchange.


|x
|1..1
|<<Reactance,Reactance>>
|
Positive sequence reactance. Used to represent Extended-Ward (IEC 60909).

Usage : Extended-Ward is a result of network reduction prior to the data exchange.


|x0
|1..1
|<<Reactance,Reactance>>
|
Zero sequence reactance. Used to represent Extended-Ward (IEC 60909).

Usage : Extended-Ward is a result of network reduction prior to the data exchange.


|x2
|1..1
|<<Reactance,Reactance>>
|
Negative sequence reactance. Used to represent Extended-Ward (IEC 60909).

Usage : Extended-Ward is a result of network reduction prior to the data exchange.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ExternalNetworkInjection]
==== (Description) ExternalNetworkInjection

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

This class represents the external network and it is used for IEC 60909 calculations.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|ikSecond
|0..1
|<<Boolean,Boolean>>
|
Indicates whether initial symmetrical short-circuit current and power have been calculated according to IEC (Ik"). Used only if short circuit calculations are done according to superposition method.


|maxInitialSymShCCurrent
|1..1
|<<CurrentFlow,CurrentFlow>>
|
Maximum initial symmetrical short-circuit currents (Ik" max) in A (Ik" = Sk"/(SQRT(3) Un)). Used for short circuit data exchange according to IEC 60909.


|maxR0ToX0Ratio
|1..1
|<<Float,Float>>
|
Maximum ratio of zero sequence resistance of Network Feeder to its zero sequence reactance (R(0)/X(0) max). Used for short circuit data exchange according to IEC 60909.


|maxR1ToX1Ratio
|1..1
|<<Float,Float>>
|
Maximum ratio of positive sequence resistance of Network Feeder to its positive sequence reactance (R(1)/X(1) max). Used for short circuit data exchange according to IEC 60909.


|maxZ0ToZ1Ratio
|1..1
|<<Float,Float>>
|
Maximum ratio of zero sequence impedance to its positive sequence impedance (Z(0)/Z(1) max). Used for short circuit data exchange according to IEC 60909.


|minInitialSymShCCurrent
|1..1
|<<CurrentFlow,CurrentFlow>>
|
Minimum initial symmetrical short-circuit currents (Ik" min) in A (Ik" = Sk"/(SQRT(3) Un)). Used for short circuit data exchange according to IEC 60909.


|minR0ToX0Ratio
|1..1
|<<Float,Float>>
|
Indicates whether initial symmetrical short-circuit current and power have been calculated according to IEC (Ik"). Used for short circuit data exchange according to IEC 6090.


|minR1ToX1Ratio
|1..1
|<<Float,Float>>
|
Minimum ratio of positive sequence resistance of Network Feeder to its positive sequence reactance (R(1)/X(1) min). Used for short circuit data exchange according to IEC 60909.


|minZ0ToZ1Ratio
|1..1
|<<Float,Float>>
|
Minimum ratio of zero sequence impedance to its positive sequence impedance (Z(0)/Z(1) min). Used for short circuit data exchange according to IEC 60909.


|voltageFactor
|0..1
|<<PU,PU>>
|
Voltage factor in pu, which was used to calculate short-circuit current Ik" and power Sk". Used only if short circuit calculations are done according to superposition method.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#GroundingImpedance]
==== (Description) GroundingImpedance

Inheritance path = <<EarthFaultCompensator,EarthFaultCompensator>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A fixed impedance device used for grounding.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|x
|1..1
|<<Reactance,Reactance>>
|
Reactance of device.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|r
|0..1
|<<Resistance,Resistance>>
|see <<EarthFaultCompensator,EarthFaultCompensator>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#LinearShuntCompensator]
==== (Description) LinearShuntCompensator

Inheritance path = <<ShuntCompensator,ShuntCompensator>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A linear shunt compensator has banks or sections with equal admittance values.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|b0PerSection
|1..1
|<<Susceptance,Susceptance>>
|
Zero sequence shunt (charging) susceptance per section.


|g0PerSection
|1..1
|<<Conductance,Conductance>>
|
Zero sequence shunt (charging) conductance per section.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#MutualCoupling]
==== MutualCoupling

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

This class represents the zero sequence line mutual coupling.

The terminals (first terminal and second terminal) associated with the mutual coupling must have sequence number set. The terminals must be associated with two different AC line segments.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|b0ch
|1..1
|<<Susceptance,Susceptance>>
|
Zero sequence mutual coupling shunt (charging) susceptance, uniformly distributed, of the entire line section.


|distance11
|1..1
|<<Length,Length>>
|
Distance to the start of the coupled region from the first line's terminal having sequence number equal to 1.


|distance12
|1..1
|<<Length,Length>>
|
Distance to the end of the coupled region from the first line's terminal with sequence number equal to 1.


|distance21
|1..1
|<<Length,Length>>
|
Distance to the start of coupled region from the second line's terminal with sequence number equal to 1.


|distance22
|1..1
|<<Length,Length>>
|
Distance to the end of coupled region from the second line's terminal with sequence number equal to 1.


|g0ch
|1..1
|<<Conductance,Conductance>>
|
Zero sequence mutual coupling shunt (charging) conductance, uniformly distributed, of the entire line section.


|r0
|1..1
|<<Resistance,Resistance>>
|
Zero sequence branch-to-branch mutual impedance coupling, resistance.


|x0
|1..1
|<<Reactance,Reactance>>
|
Zero sequence branch-to-branch mutual impedance coupling, reactance.


|First_Terminal
|1..1
|<<Terminal,Terminal>>
|
The starting terminal for the calculation of distances along the first branch of the mutual coupling. Normally MutualCoupling would only be used for terminals of AC line segments. The first and second terminals of a mutual coupling should point to different AC line segments.


|Second_Terminal
|1..1
|<<Terminal,Terminal>>
|
The starting terminal for the calculation of distances along the second branch of the mutual coupling.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#NonlinearShuntCompensatorPoint]
==== (Description) NonlinearShuntCompensatorPoint


A non linear shunt compensator bank or section admittance value. The number of NonlinearShuntCompenstorPoint instances associated with a NonlinearShuntCompensator shall be equal to ShuntCompensator.maximumSections. ShuntCompensator.sections shall only be set to one of the NonlinearShuntCompenstorPoint.sectionNumber. There is no interpolation between NonlinearShuntCompenstorPoint-s.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|b0
|1..1
|<<Susceptance,Susceptance>>
|
Zero sequence shunt (charging) susceptance per section.


|g0
|1..1
|<<Conductance,Conductance>>
|
Zero sequence shunt (charging) conductance per section.

|===

[#PetersenCoil]
==== (Description) PetersenCoil

Inheritance path = <<EarthFaultCompensator,EarthFaultCompensator>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A variable impedance device normally used to offset line charging during single line faults in an ungrounded section of network.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|mode (enumeration)
|1..1
|<<PetersenCoilModeKind,PetersenCoilModeKind>>
|
The mode of operation of the Petersen coil.


|nominalU
|1..1
|<<Voltage,Voltage>>
|
The nominal voltage for which the coil is designed.


|offsetCurrent
|0..1
|<<CurrentFlow,CurrentFlow>>
|
The offset current that the Petersen coil controller is operating from the resonant point. This is normally a fixed amount for which the controller is configured and could be positive or negative. Typically 0 to 60 A depending on voltage and resonance conditions.


|positionCurrent
|0..1
|<<CurrentFlow,CurrentFlow>>
|
The control current used to control the Petersen coil also known as the position current. Typically in the range of 20 mA to 200 mA.


|xGroundMax
|1..1
|<<Reactance,Reactance>>
|
The maximum reactance.


|xGroundMin
|1..1
|<<Reactance,Reactance>>
|
The minimum reactance.


|xGroundNominal
|1..1
|<<Reactance,Reactance>>
|
The nominal reactance. This is the operating point (normally over compensation) that is defined based on the resonance point in the healthy network condition. The impedance is calculated based on nominal voltage divided by position current.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|r
|0..1
|<<Resistance,Resistance>>
|see <<EarthFaultCompensator,EarthFaultCompensator>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PowerTransformer]
==== (Description) PowerTransformer

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

An electrical device consisting of two or more coupled windings, with or without a magnetic core, for introducing mutual coupling between electric circuits. Transformers can be used to control voltage and phase shift (active power flow).

A power transformer may be composed of separate transformer tanks that need not be identical.

A power transformer can be modelled with or without tanks and is intended for use in both balanced and unbalanced representations. A power transformer typically has two terminals, but may have one (grounding), three or more terminals.

The inherited association ConductingEquipment.BaseVoltage should not be used. The association from TransformerEnd to BaseVoltage should be used instead.




*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|beforeShCircuitHighestOperatingCurrent
|0..1
|<<CurrentFlow,CurrentFlow>>
|
The highest operating current (Ib in IEC 60909-0) before short circuit (depends on network configuration and relevant reliability philosophy). It is used for calculation of the impedance correction factor KT defined in IEC 60909-0.


|beforeShCircuitHighestOperatingVoltage
|0..1
|<<Voltage,Voltage>>
|
The highest operating voltage (Ub in IEC 60909-0) before short circuit. It is used for calculation of the impedance correction factor KT defined in IEC 60909-0. This is worst case voltage on the low side winding (3.7.1 of IEC 60909:2001). Used to define operating conditions.


|beforeShortCircuitAnglePf
|0..1
|<<AngleDegrees,AngleDegrees>>
|
The angle of power factor before short circuit (phib in IEC 60909-0). It is used for calculation of the impedance correction factor KT defined in IEC 60909-0. This is the worst case power factor. Used to define operating conditions.


|highSideMinOperatingU
|0..1
|<<Voltage,Voltage>>
|
The minimum operating voltage (uQmin in IEC 60909-0) at the high voltage side (Q side) of the unit transformer of the power station unit. A value well established from long-term operating experience of the system. It is used for calculation of the impedance correction factor KG defined in IEC 60909-0.


|isPartOfGeneratorUnit
|1..1
|<<Boolean,Boolean>>
|
Indicates whether the machine is part of a power station unit. Used for short circuit data exchange according to IEC 60909. It has an impact on how the correction factors are calculated for transformers, since the transformer is not necessarily part of a synchronous machine and generating unit. It is not always possible to derive this information from the model. This is why the attribute is necessary.


|operationalValuesConsidered
|0..1
|<<Boolean,Boolean>>
|
It is used to define if the data (other attributes related to short circuit data exchange) defines long term operational conditions or not. Used for short circuit data exchange according to IEC 60909.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PowerTransformerEnd]
==== (Description) PowerTransformerEnd

Inheritance path = <<TransformerEnd,TransformerEnd>> => <<IdentifiedObject,IdentifiedObject>>

A PowerTransformerEnd is associated with each Terminal of a PowerTransformer.

The impedance values r, r0, x, and x0 of a PowerTransformerEnd represents a star equivalent as follows.

1) for a two Terminal PowerTransformer the high voltage (TransformerEnd.endNumber=1) PowerTransformerEnd has non zero values on r, r0, x, and x0 while the low voltage (TransformerEnd.endNumber=2) PowerTransformerEnd has zero values for r, r0, x, and x0. Parameters are always provided, even if the PowerTransformerEnds have the same rated voltage. In this case, the parameters are provided at the PowerTransformerEnd which has TransformerEnd.endNumber equal to 1.

2) for a three Terminal PowerTransformer the three PowerTransformerEnds represent a star equivalent with each leg in the star represented by r, r0, x, and x0 values.

3) For a three Terminal transformer each PowerTransformerEnd shall have g, g0, b and b0 values corresponding to the no load losses distributed on the three PowerTransformerEnds. The total no load loss shunt impedances may also be placed at one of the PowerTransformerEnds, preferably the end numbered 1, having the shunt values on end 1. This is the preferred way.

4) for a PowerTransformer with more than three Terminals the PowerTransformerEnd impedance values cannot be used. Instead use the TransformerMeshImpedance or split the transformer into multiple PowerTransformers.

Each PowerTransformerEnd must be contained by a PowerTransformer. Because a PowerTransformerEnd (or any other object) can not be contained by more than one parent, a PowerTransformerEnd can not have an association to an EquipmentContainer (Substation, VoltageLevel, etc).




*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|b0
|1..1
|<<Susceptance,Susceptance>>
|
Zero sequence magnetizing branch susceptance.


|g0
|1..1
|<<Conductance,Conductance>>
|
Zero sequence magnetizing branch conductance (star-model).


|phaseAngleClock
|1..1
|<<Integer,Integer>>
|
Terminal voltage phase angle displacement where 360 degrees are represented with clock hours. The valid values are 0 to 11. For example, for the secondary side end of a transformer with vector group code of 'Dyn11', specify the connection kind as wye with neutral and specify the phase angle of the clock as 11. The clock value of the transformer end number specified as 1, is assumed to be zero. Note the transformer end number is not assumed to be the same as the terminal sequence number.


|r0
|1..1
|<<Resistance,Resistance>>
|
Zero sequence series resistance (star-model) of the transformer end.


|x0
|1..1
|<<Reactance,Reactance>>
|
Zero sequence series reactance of the transformer end.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|grounded
|1..1
|boolean
|see <<TransformerEnd,TransformerEnd>>

|rground
|0..1
|<<Resistance,Resistance>>
|see <<TransformerEnd,TransformerEnd>>

|xground
|0..1
|<<Reactance,Reactance>>
|see <<TransformerEnd,TransformerEnd>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#SeriesCompensator]
==== (Description) SeriesCompensator

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A Series Compensator is a series capacitor or reactor or an AC transmission line without charging susceptance. It is a two terminal device.




*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|r0
|1..1
|<<Resistance,Resistance>>
|
Zero sequence resistance.


|varistorPresent
|1..1
|<<Boolean,Boolean>>
|
Describe if a metal oxide varistor (mov) for over voltage protection is configured in parallel with the series compensator. It is used for short circuit calculations.


|varistorRatedCurrent
|0..1
|<<CurrentFlow,CurrentFlow>>
|
The maximum current the varistor is designed to handle at specified duration. It is used for short circuit calculations and exchanged only if SeriesCompensator.varistorPresent is true.

The attribute shall be a positive value.


|varistorVoltageThreshold
|0..1
|<<Voltage,Voltage>>
|
The dc voltage at which the varistor starts conducting. It is used for short circuit calculations and exchanged only if SeriesCompensator.varistorPresent is true.


|x0
|1..1
|<<Reactance,Reactance>>
|
Zero sequence reactance.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#SynchronousMachine]
==== (Description) SynchronousMachine

Inheritance path = <<RotatingMachine,RotatingMachine>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

An electromechanical device that operates with shaft rotating synchronously with the network. It is a single machine operating either as a generator or synchronous condenser or pump.




*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|earthing
|1..1
|<<Boolean,Boolean>>
|
Indicates whether or not the generator is earthed. Used for short circuit data exchange according to IEC 60909.


|earthingStarPointR
|0..1
|<<Resistance,Resistance>>
|
Generator star point earthing resistance (Re). Used for short circuit data exchange according to IEC 60909.


|earthingStarPointX
|0..1
|<<Reactance,Reactance>>
|
Generator star point earthing reactance (Xe). Used for short circuit data exchange according to IEC 60909.


|ikk
|0..1
|<<CurrentFlow,CurrentFlow>>
|
Steady-state short-circuit current (in A for the profile) of generator with compound excitation during 3-phase short circuit.

- Ikk=0: Generator with no compound excitation.

- Ikk&lt;&gt;0: Generator with compound excitation.

Ikk is used to calculate the minimum steady-state short-circuit current for generators with compound excitation.

(4.6.1.2 in IEC 60909-0:2001).

Used only for single fed short circuit on a generator. (4.3.4.2. in IEC 60909-0:2001).


|mu
|0..1
|<<Float,Float>>
|
Factor to calculate the breaking current (Section 4.5.2.1 in IEC 60909-0).

Used only for single fed short circuit on a generator (Section 4.3.4.2. in IEC 60909-0).


|r
|1..1
|<<Resistance,Resistance>>
|
Equivalent resistance (RG) of generator. RG is considered for the calculation of all currents, except for the calculation of the peak current ip. Used for short circuit data exchange according to IEC 60909.


|r0
|1..1
|<<Resistance,Resistance>>
|
Zero sequence resistance of the synchronous machine.


|r2
|1..1
|<<Resistance,Resistance>>
|
Negative sequence resistance.


|satDirectSubtransX
|1..1
|<<PU,PU>>
|
Direct-axis subtransient reactance saturated, also known as Xd"sat.


|satDirectSyncX
|0..1
|<<PU,PU>>
|
Direct-axes saturated synchronous reactance (xdsat); reciprocal of short-circuit ration. Used for short circuit data exchange, only for single fed short circuit on a generator. (4.3.4.2. in IEC 60909-0:2001).


|satDirectTransX
|0..1
|<<PU,PU>>
|
Saturated Direct-axis transient reactance. The attribute is primarily used for short circuit calculations according to ANSI.


|shortCircuitRotorType (enumeration)
|0..1
|<<ShortCircuitRotorKind,ShortCircuitRotorKind>>
|
Type of rotor, used by short circuit applications, only for single fed short circuit according to IEC 60909.


|voltageRegulationRange
|0..1
|<<PerCent,PerCent>>
|
Range of generator voltage regulation (PG in IEC 60909-0) used for calculation of the impedance correction factor KG defined in IEC 60909-0.

This attribute is used to describe the operating voltage of the generating unit.


|x0
|1..1
|<<Reactance,Reactance>>
|
Zero sequence reactance of the synchronous machine.


|x2
|1..1
|<<Reactance,Reactance>>
|
Negative sequence reactance.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===


=== Abstract Classes

[#ACDCTerminal]
==== ACDCTerminal

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

An electrical connection point (AC or DC) to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ConductingEquipment]
==== ConductingEquipment

Inheritance path = <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The parts of the AC power system that are designed to carry current or that are conductively connected through terminals.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Conductor]
==== Conductor

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Combination of conducting material with consistent electrical characteristics, building a single electrical system, used to carry current between points in the power system.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Connector]
==== Connector

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A conductor, or group of conductors, with negligible impedance, that serve to connect other conducting equipment within a single substation and are modelled with a single logical terminal.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EarthFaultCompensator]
==== EarthFaultCompensator

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A conducting equipment used to represent a connection to ground which is typically used to compensate earth faults. An earth fault compensator device modelled with a single terminal implies a second terminal solidly connected to ground. If two terminals are modelled, the ground is not assumed and normal connection rules apply.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|r
|0..1
|<<Resistance,Resistance>>
|
Nominal resistance of device.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EnergyConnection]
==== EnergyConnection

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A connection of energy generation or consumption on the power system model.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Equipment]
==== Equipment

Inheritance path = <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The parts of a power system that are physical devices, electronic or mechanical.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EquivalentEquipment]
==== EquivalentEquipment

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The class represents equivalent objects that are the result of a network reduction. The class is the base for equivalent objects of different types.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#IdentifiedObject]
==== IdentifiedObject


This is a root class to provide common identification for all classes needing identification and naming attributes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|mRID
|1..1
|<<String,String>>
|
Master resource identifier issued by a model authority. The mRID is unique within an exchange context. Global uniqueness is easily achieved by using a UUID, as specified in RFC 4122, for the mRID. The use of UUID is strongly recommended.

For CIMXML data files in RDF syntax conforming to IEC 61970-552, the mRID is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.

|===

[#PowerSystemResource]
==== PowerSystemResource

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

A power system resource (PSR) can be an item of equipment such as a switch, an equipment container containing many individual items of equipment such as a substation, or an organisational entity such as sub-control area. Power system resources can have measurements associated.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RegulatingCondEq]
==== RegulatingCondEq

Inheritance path = <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A type of conducting equipment that can regulate a quantity (i.e. voltage or flow) at a specific point in the network.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RotatingMachine]
==== RotatingMachine

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A rotating machine which may be used as a generator or motor.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ShuntCompensator]
==== ShuntCompensator

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A shunt capacitor or reactor or switchable bank of shunt capacitors or reactors. A section of a shunt compensator is an individual capacitor or reactor. A negative value for bPerSection indicates that the compensator is a reactor. ShuntCompensator is a single terminal device. Ground is implied.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Terminal]
==== Terminal

Inheritance path = <<ACDCTerminal,ACDCTerminal>> => <<IdentifiedObject,IdentifiedObject>>

An AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#TransformerEnd]
==== TransformerEnd

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

A conducting connection point of a power transformer. It corresponds to a physical transformer winding terminal. In earlier CIM versions, the TransformerWinding class served a similar purpose, but this class is more flexible because it associates to terminal but is not a specialization of ConductingEquipment.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|grounded
|1..1
|<<Boolean,Boolean>>
|
(for Yn and Zn connections) True if the neutral is solidly grounded.


|rground
|0..1
|<<Resistance,Resistance>>
|
(for Yn and Zn connections) Resistance part of neutral impedance where 'grounded' is true.


|xground
|0..1
|<<Reactance,Reactance>>
|
(for Yn and Zn connections) Reactive part of neutral impedance where 'grounded' is true.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===



=== Enumerations

[#PetersenCoilModeKind]
==== PetersenCoilModeKind

The mode of operation for a Petersen coil.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|automaticPositioning
|
Automatic positioning.


|fixed
|
Fixed position.


|manual
|
Manual positioning.

|===
[#ShortCircuitRotorKind]
==== ShortCircuitRotorKind

Type of rotor, used by short circuit applications.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|salientPole1
|
Salient pole 1 in IEC 60909.


|salientPole2
|
Salient pole 2 in IEC 60909.


|turboSeries1
|
Turbo Series 1 in IEC 60909.


|turboSeries2
|
Turbo series 2 in IEC 60909.

|===
[#UnitMultiplier]
==== UnitMultiplier

The unit multipliers defined for the CIM. When applied to unit symbols, the unit symbol is treated as a derived unit. Regardless of the contents of the unit symbol text, the unit symbol shall be treated as if it were a single-character unit symbol. Unit symbols should not contain multipliers, and it should be left to the multiplier to define the multiple for an entire data type.

For example, if a unit symbol is "m2Pers" and the multiplier is "k", then the value is k(m**2/s), and the multiplier applies to the entire final value, not to any individual part of the value. This can be conceptualized by substituting a derived unit symbol for the unit type. If one imagines that the symbol "" represents the derived unit "m2Pers", then applying the multiplier "k" can be conceptualized simply as "k".

For example, the SI unit for mass is "kg" and not "g". If the unit symbol is defined as "kg", then the multiplier is applied to "kg" as a whole and does not replace the "k" in front of the "g". In this case, the multiplier of "m" would be used with the unit symbol of "kg" to represent one gram. As a text string, this violates the instructions in IEC 80000-1. However, because the unit symbol in CIM is treated as a derived unit instead of as an SI unit, it makes more sense to conceptualize the "kg" as if it were replaced by one of the proposed replacements for the SI mass symbol. If one imagines that the "kg" were replaced by a symbol "", then it is easier to conceptualize the multiplier "m" as creating the proper unit "m", and not the forbidden unit "mkg".


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|E
|
Exa 10**18.


|G
|
Giga 10**9.


|M
|
Mega 10**6.


|P
|
Peta 10**15.


|T
|
Tera 10**12.


|Y
|
Yotta 10**24.


|Z
|
Zetta 10**21.


|a
|
Atto 10**-18.


|c
|
Centi 10**-2.


|d
|
Deci 10**-1.


|da
|
Deca 10**1.


|f
|
Femto 10**-15.


|h
|
Hecto 10**2.


|k
|
Kilo 10**3.


|m
|
Milli 10**-3.


|micro
|
Micro 10**-6.


|n
|
Nano 10**-9.


|none
|
No multiplier or equivalently multiply by 1.


|p
|
Pico 10**-12.


|y
|
Yocto 10**-24.


|z
|
Zepto 10**-21.

|===
[#UnitSymbol]
==== UnitSymbol

The derived units defined for usage in the CIM. In some cases, the derived unit is equal to an SI unit. Whenever possible, the standard derived symbol is used instead of the formula for the derived unit. For example, the unit symbol Farad is defined as "F" instead of "CPerV". In cases where a standard symbol does not exist for a derived unit, the formula for the unit is used as the unit symbol. For example, density does not have a standard symbol and so it is represented as "kgPerm3". With the exception of the "kg", which is an SI unit, the unit symbols do not contain multipliers and therefore represent the base derived unit to which a multiplier can be applied as a whole.

Every unit symbol is treated as an unparseable text as if it were a single-letter symbol. The meaning of each unit symbol is defined by the accompanying descriptive text and not by the text contents of the unit symbol.

To allow the widest possible range of serializations without requiring special character handling, several substitutions are made which deviate from the format described in IEC 80000-1. The division symbol "/" is replaced by the letters "Per". Exponents are written in plain text after the unit as "m3" instead of being formatted as "m" with a superscript of 3 or introducing a symbol as in "m^3". The degree symbol "" is replaced with the letters "deg". Any clarification of the meaning for a substitution is included in the description for the unit symbol.

Non-SI units are included in list of unit symbols to allow sources of data to be correctly labelled with their non-SI units (for example, a GPS sensor that is reporting numbers that represent feet instead of meters). This allows software to use the unit symbol information correctly convert and scale the raw data of those sources into SI-based units.

The integer values are used for harmonization with IEC 61850.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|A
|
Current in amperes.


|A2
|
Amperes squared (A).


|A2h
|
Ampere-squared hour, ampere-squared hour.


|A2s
|
Ampere squared time in square amperes (As).


|APerA
|
Current, ratio of amperages. Note: Users may need to supply a prefix such as m to show rates such as mA/A.


|APerm
|
A/m, magnetic field strength, amperes per metre.


|Ah
|
Ampere-hours, ampere-hours.


|As
|
Ampere seconds (As).


|Bq
|
Radioactivity in becquerels (1/s).


|Btu
|
Energy, British Thermal Units.


|C
|
Electric charge in coulombs (As).


|CPerkg
|
Exposure (x rays), coulombs per kilogram.


|CPerm2
|
Surface charge density, coulombs per square metre.


|CPerm3
|
Electric charge density, coulombs per cubic metre.


|F
|
Electric capacitance in farads (C/V).


|FPerm
|
Permittivity, farads per metre.


|G
|
Magnetic flux density, gausses (1 G = 10-4 T).


|Gy
|
Absorbed dose in grays (J/kg).


|GyPers
|
Absorbed dose rate, grays per second.


|H
|
Electric inductance in henrys (Wb/A).


|HPerm
|
Permeability, henrys per metre.


|Hz
|
Frequency in hertz (1/s).


|HzPerHz
|
Frequency, rate of frequency change. Note: Users may need to supply a prefix such as m to show rates such as mHz/Hz.


|HzPers
|
Rate of change of frequency in hertz per second.


|J
|
Energy in joules (Nm = CV = Ws).


|JPerK
|
Heat capacity in joules/kelvin.


|JPerkg
|
Specific energy, Joules / kg.


|JPerkgK
|
Specific heat capacity, specific entropy, joules per kilogram Kelvin.


|JPerm2
|
Insulation energy density, joules per square metre or watt second per square metre.


|JPerm3
|
Energy density, joules per cubic metre.


|JPermol
|
Molar energy, joules per mole.


|JPermolK
|
Molar entropy, molar heat capacity, joules per mole kelvin.


|JPers
|
Energy rate in joules per second (J/s).


|K
|
Temperature in kelvins.


|KPers
|
Temperature change rate in kelvins per second.


|M
|
Length, nautical miles (1 M = 1852 m).


|Mx
|
Magnetic flux, maxwells (1 Mx = 10-8 Wb).


|N
|
Force in newtons (kgm/s).


|NPerm
|
Surface tension, newton per metre.


|Nm
|
Moment of force, newton metres.


|Oe
|
Magnetic field in oersteds, (1 Oe = (103/4p) A/m).


|Pa
|
Pressure in pascals (N/m). Note: the absolute or relative measurement of pressure is implied with this entry. See below for more explicit forms.


|PaPers
|
Pressure change rate in pascals per second.


|Pas
|
Dynamic viscosity, pascal seconds.


|Q
|
Quantity power, Q.


|Qh
|
Quantity energy, Qh.


|S
|
Conductance in siemens.


|SPerm
|
Conductance per length (F/m).


|Sv
|
Dose equivalent in sieverts (J/kg).


|T
|
Magnetic flux density in teslas (Wb/m2).


|V
|
Electric potential in volts (W/A).


|V2
|
Volt squared (W/A).


|V2h
|
Volt-squared hour, volt-squared-hours.


|VA
|
Apparent power in volt amperes. See also real power and reactive power.


|VAh
|
Apparent energy in volt ampere hours.


|VAr
|
Reactive power in volt amperes reactive. The reactive or imaginary component of electrical power (VIsin(phi)). (See also real power and apparent power).

Note: Different meter designs use different methods to arrive at their results. Some meters may compute reactive power as an arithmetic value, while others compute the value vectorially. The data consumer should determine the method in use and the suitability of the measurement for the intended purpose.


|VArh
|
Reactive energy in volt ampere reactive hours.


|VPerHz
|
Magnetic flux in volt per hertz.


|VPerV
|
Voltage, ratio of voltages. Note: Users may need to supply a prefix such as m to show rates such as mV/V.


|VPerVA
|
Power factor, PF, the ratio of the active power to the apparent power. Note: The sign convention used for power factor will differ between IEC meters and EEI (ANSI) meters. It is assumed that the data consumers understand the type of meter being used and agree on the sign convention in use at any given utility.


|VPerVAr
|
Power factor, PF, the ratio of the active power to the apparent power. Note: The sign convention used for power factor will differ between IEC meters and EEI (ANSI) meters. It is assumed that the data consumers understand the type of meter being used and agree on the sign convention in use at any given utility.


|VPerm
|
Electric field strength, volts per metre.


|Vh
|
Volt-hour, Volt hours.


|Vs
|
Volt seconds (Ws/A).


|W
|
Real power in watts (J/s). Electrical power may have real and reactive components. The real portion of electrical power (I&#178;R or VIcos(phi)), is expressed in Watts. See also apparent power and reactive power.


|WPerA
|
Active power per current flow, watts per Ampere.


|WPerW
|
Signal Strength, ratio of power. Note: Users may need to supply a prefix such as m to show rates such as mW/W.


|WPerm2
|
Heat flux density, irradiance, watts per square metre.


|WPerm2sr
|
Radiance, watts per square metre steradian.


|WPermK
|
Thermal conductivity in watt/metres kelvin.


|WPers
|
Ramp rate in watts per second.


|WPersr
|
Radiant intensity, watts per steradian.


|Wb
|
Magnetic flux in webers (Vs).


|Wh
|
Real energy in watt hours.


|anglemin
|
Plane angle, minutes.


|anglesec
|
Plane angle, seconds.


|bar
|
Pressure in bars, (1 bar = 100 kPa).


|cd
|
Luminous intensity in candelas.


|charPers
|
Data rate (baud) in characters per second.


|character
|
Number of characters.


|cosPhi
|
Power factor, dimensionless.

Note 1: This definition of power factor only holds for balanced systems. See the alternative definition under code 153.

Note 2: Beware of differing sign conventions in use between the IEC and EEI. It is assumed that the data consumer understands the type of meter in use and the sign convention in use by the utility.


|count
|
Amount of substance, Counter value.


|d
|
Time in days, day = 24 h = 86400 s.


|dB
|
Sound pressure level in decibels. Note: multiplier d is included in this unit symbol for compatibility with IEC 61850-7-3.


|dBm
|
Power level (logarithmic ratio of signal strength , Bel-mW), normalized to 1mW. Note: multiplier d is included in this unit symbol for compatibility with IEC 61850-7-3.


|deg
|
Plane angle in degrees.


|degC
|
Relative temperature in degrees Celsius.

In the SI unit system the symbol is C. Electric charge is measured in coulomb that has the unit symbol C. To distinguish degree Celsius from coulomb the symbol used in the UML is degC. The reason for not using C is that the special character is difficult to manage in software.


|ft3
|
Volume, cubic feet.


|gPerg
|
Concentration, The ratio of the mass of a solute divided by the mass of the solution. Note: Users may need use a prefix such a to express a quantity such as g/g.


|gal
|
Volume in gallons, US gallon (1 gal = 231 in3 = 128 fl ounce).


|h
|
Time in hours, hour = 60 min = 3600 s.


|ha
|
Area, hectares.


|kat
|
Catalytic activity, katal = mol / s.


|katPerm3
|
Catalytic activity concentration, katals per cubic metre.


|kg
|
Mass in kilograms. Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgPerJ
|
Weight per energy in kilograms per joule (kg/J). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgPerm3
|
Density in kilogram/cubic metres (kg/m). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgm
|
Moment of mass in kilogram metres (kgm) (first moment of mass). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgm2
|
Moment of mass in kilogram square metres (kgm) (Second moment of mass, commonly called the moment of inertia). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kn
|
Speed, knots (1 kn = 1852/3600) m/s.


|l
|
Volume in litres, litre = dm3 = m3/1000.


|lPerh
|
Volumetric flow rate, litres per hour.


|lPerl
|
Concentration, The ratio of the volume of a solute divided by the volume of the solution. Note: Users may need use a prefix such a to express a quantity such as L/L.


|lPers
|
Volumetric flow rate in litres per second.


|lm
|
Luminous flux in lumens (cdsr).


|lx
|
Illuminance in lux (lm/m).


|m
|
Length in metres.


|m2
|
Area in square metres (m).


|m2Pers
|
Viscosity in square metres / second (m/s).


|m3
|
Volume in cubic metres (m).


|m3Compensated
|
Volume, cubic metres, with the value compensated for weather effects.


|m3Perh
|
Volumetric flow rate, cubic metres per hour.


|m3Perkg
|
Specific volume, cubic metres per kilogram, v.


|m3Pers
|
Volumetric flow rate in cubic metres per second (m/s).


|m3Uncompensated
|
Volume, cubic metres, with the value uncompensated for weather effects.


|mPerm3
|
Fuel efficiency in metres per cubic metres (m/m).


|mPers
|
Velocity in metres per second (m/s).


|mPers2
|
Acceleration in metres per second squared (m/s).


|min
|
Time in minutes, minute = 60 s.


|mmHg
|
Pressure, millimetres of mercury (1 mmHg is approximately 133.3 Pa).


|mol
|
Amount of substance in moles.


|molPerkg
|
Concentration, Molality, the amount of solute in moles and the amount of solvent in kilograms.


|molPerm3
|
Concentration, The amount of substance concentration, (c), the amount of solvent in moles divided by the volume of solution in m.


|molPermol
|
Concentration, Molar fraction, the ratio of the molar amount of a solute divided by the molar amount of the solution.


|none
|
Dimension less quantity, e.g. count, per unit, etc.


|ohm
|
Electric resistance in ohms (V/A).


|ohmPerm
|
Electric resistance per length in ohms per metre ((V/A)/m).


|ohmm
|
Resistivity, ohm metres, (rho).


|onePerHz
|
Reciprocal of frequency (1/Hz).


|onePerm
|
Wavenumber, reciprocal metres, (1/m).


|ppm
|
Concentration in parts per million.


|rad
|
Plane angle in radians (m/m).


|radPers
|
Angular velocity in radians per second (rad/s).


|radPers2
|
Angular acceleration, radians per second squared.


|rev
|
Amount of rotation, revolutions.


|rotPers
|
Rotations per second (1/s). See also Hz (1/s).


|s
|
Time in seconds.


|sPers
|
Time, Ratio of time. Note: Users may need to supply a prefix such as &#181; to show rates such as &#181;s/s.


|sr
|
Solid angle in steradians (m2/m2).


|therm
|
Energy, therms.


|tonne
|
Mass in tons, tonne or metric ton (1000 kg = 1 Mg).

|===

=== Datatypes

[#ActivePower]
==== ActivePower

Product of RMS value of the voltage and the RMS value of the in-phase component of the current.


XSD type: float

[#AngleDegrees]
==== AngleDegrees

Measurement of angle in degrees.


XSD type: float

[#Conductance]
==== Conductance

Factor by which voltage must be multiplied to give corresponding power lost from a circuit. Real part of admittance.


XSD type: float

[#CurrentFlow]
==== CurrentFlow

Electrical current with sign convention: positive flow is out of the conducting equipment into the connectivity node. Can be both AC and DC.


XSD type: float

[#Length]
==== Length

Unit of length. It shall be a positive value or zero.


XSD type: float

[#PU]
==== PU

Per Unit - a positive or negative value referred to a defined base. Values typically range from -10 to +10.


XSD type: float

[#PerCent]
==== PerCent

Percentage on a defined base. For example, specify as 100 to indicate at the defined base.


XSD type: float

[#Reactance]
==== Reactance

Reactance (imaginary part of impedance), at rated frequency.


XSD type: float

[#Resistance]
==== Resistance

Resistance (real part of impedance).


XSD type: float

[#Susceptance]
==== Susceptance

Imaginary part of admittance.


XSD type: float

[#Temperature]
==== Temperature

Value of temperature in degrees Celsius.


XSD type: float

[#Voltage]
==== Voltage

Electrical voltage, can be both AC and DC.


XSD type: float


=== Primitive Types

[#CGMES-ShortCircuit-Boolean]
==== Boolean

A type with the value space "true" and "false".


XSD type: boolean

[#CGMES-ShortCircuit-Float]
==== Float

A floating point number. The range is unspecified and not limited.


XSD type: float

[#CGMES-ShortCircuit-Integer]
==== Integer

An integer number. The range is unspecified and not limited.


XSD type: integer

[#CGMES-ShortCircuit-String]
==== String

A string consisting of a sequence of characters. The character encoding is UTF-8. The string length is unspecified and unlimited.


XSD type: string

