:pdf-themesdir: {docdir}
:pdf-theme: adoc-inline-rdfs

== Operation Profile Specification

// Settings:
:doctype: inline
:reproducible:
:icons: font
:sectnums:

Profile namespace: http://iec.ch/TC57/ns/CIM/Operation-EU/3.0#

plantuml::./Profiles/CGMES-Operation.rdfs-t2b.puml[format=svg, align=center, caption="Figure 1: ", title="Operation Profile"]

== Profile Specification

This profile represents the equipment of the power system and their hierarchical relationships.


=== Concrete Classes

[#Accumulator]
==== Accumulator

Inheritance path = <<Measurement,Measurement>> => <<IdentifiedObject,IdentifiedObject>>

Accumulator represents an accumulated (counted) Measurement, e.g. an energy value.

The association to Terminal may not be required depending on how the Measurement is being used. See section Use of Measurement Class for details.

The measurementType attribute is used to define the quantity being measured (Voltage, ThreePhaseActivePower, etc.) by a Measurement. The valid values for measurementType are defined in Normative String Tables.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|measurementType
|1..1
|string
|see <<Measurement,Measurement>>

|phases (enumeration)
|0..1
|<<PhaseCode,PhaseCode>>
|see <<Measurement,Measurement>>

|unitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Measurement,Measurement>>

|unitSymbol (enumeration)
|1..1
|<<UnitSymbol,UnitSymbol>>
|see <<Measurement,Measurement>>

|PowerSystemResource
|1..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Measurement,Measurement>>

|Terminal
|0..1
|<<ACDCTerminal,ACDCTerminal>>
|see <<Measurement,Measurement>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AccumulatorLimit]
==== AccumulatorLimit

Inheritance path = <<Limit,Limit>> => <<IdentifiedObject,IdentifiedObject>>

Limit values for Accumulator measurements.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<Integer,Integer>>
|
The value to supervise against. The value is positive.


|LimitSet
|1..1
|<<AccumulatorLimitSet,AccumulatorLimitSet>>
|
The set of limits.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AccumulatorLimitSet]
==== AccumulatorLimitSet

Inheritance path = <<LimitSet,LimitSet>> => <<IdentifiedObject,IdentifiedObject>>

An AccumulatorLimitSet specifies a set of Limits that are associated with an Accumulator measurement.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|Measurements
|1..*
|<<Accumulator,Accumulator>>
|
The Measurements using the LimitSet.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|isPercentageLimits
|0..1
|boolean
|see <<LimitSet,LimitSet>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AccumulatorReset]
==== AccumulatorReset

Inheritance path = <<Control,Control>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

This command resets the counter value to zero.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|AccumulatorValue
|1..1
|<<AccumulatorValue,AccumulatorValue>>
|
The accumulator value that is reset by the command.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlType
|1..1
|string
|see <<Control,Control>>

|operationInProgress
|0..1
|boolean
|see <<Control,Control>>

|timeStamp
|0..1
|dateTime
|see <<Control,Control>>

|unitMultiplier (enumeration)
|0..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Control,Control>>

|unitSymbol (enumeration)
|0..1
|<<UnitSymbol,UnitSymbol>>
|see <<Control,Control>>

|PowerSystemResource
|0..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Control,Control>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AccumulatorValue]
==== AccumulatorValue

Inheritance path = <<MeasurementValue,MeasurementValue>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

AccumulatorValue represents an accumulated (counted) MeasurementValue.

- In the context of this profile this class is only used to define measurements that are available via ICCP. It is not used to supply values for those measurements. Consequently the value attribute is not included in this profile.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|Accumulator
|1..1
|<<Accumulator,Accumulator>>
|
Measurement to which this value is connected.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|sensorAccuracy
|0..1
|<<PerCent,PerCent>>
|see <<MeasurementValue,MeasurementValue>>

|timeStamp
|0..1
|dateTime
|see <<MeasurementValue,MeasurementValue>>

|MeasurementValueSource
|1..1
|<<MeasurementValueSource,MeasurementValueSource>>
|see <<MeasurementValue,MeasurementValue>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Analog]
==== Analog

Inheritance path = <<Measurement,Measurement>> => <<IdentifiedObject,IdentifiedObject>>

Analog represents an analog Measurement.

The positiveFlowIn attribute is only required if the Measurement measures a directional flow of power.

The association to Terminal may not be required depending on how the Measurement is being used. See section Use of Measurement Class for details.

The measurementType attribute is used to define the quantity being measured (Voltage, ThreePhaseActivePower, etc.) by a Measurement. The valid values for measurementType are defined in Normative String Tables.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|positiveFlowIn
|0..1
|<<Boolean,Boolean>>
|
If true then this measurement is an active power, reactive power or current with the convention that a positive value measured at the Terminal means power is flowing into the related PowerSystemResource.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|measurementType
|1..1
|string
|see <<Measurement,Measurement>>

|phases (enumeration)
|0..1
|<<PhaseCode,PhaseCode>>
|see <<Measurement,Measurement>>

|unitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Measurement,Measurement>>

|unitSymbol (enumeration)
|1..1
|<<UnitSymbol,UnitSymbol>>
|see <<Measurement,Measurement>>

|PowerSystemResource
|1..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Measurement,Measurement>>

|Terminal
|0..1
|<<ACDCTerminal,ACDCTerminal>>
|see <<Measurement,Measurement>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AnalogLimit]
==== AnalogLimit

Inheritance path = <<Limit,Limit>> => <<IdentifiedObject,IdentifiedObject>>

Limit values for Analog measurements.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<Float,Float>>
|
The value to supervise against.


|LimitSet
|1..1
|<<AnalogLimitSet,AnalogLimitSet>>
|
The set of limits.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AnalogLimitSet]
==== AnalogLimitSet

Inheritance path = <<LimitSet,LimitSet>> => <<IdentifiedObject,IdentifiedObject>>

An AnalogLimitSet specifies a set of Limits that are associated with an Analog measurement.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|Measurements
|1..*
|<<Analog,Analog>>
|
The Measurements using the LimitSet.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|isPercentageLimits
|0..1
|boolean
|see <<LimitSet,LimitSet>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AnalogValue]
==== AnalogValue

Inheritance path = <<MeasurementValue,MeasurementValue>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

AnalogValue represents an analog MeasurementValue.

- In the context of this profile this class is only used to define measurements that are available via ICCP. It is not used to supply values for those measurements. Consequently the value attribute is not included in this profile.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|Analog
|1..1
|<<Analog,Analog>>
|
Measurement to which this value is connected.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|sensorAccuracy
|0..1
|<<PerCent,PerCent>>
|see <<MeasurementValue,MeasurementValue>>

|timeStamp
|0..1
|dateTime
|see <<MeasurementValue,MeasurementValue>>

|MeasurementValueSource
|1..1
|<<MeasurementValueSource,MeasurementValueSource>>
|see <<MeasurementValue,MeasurementValue>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Command]
==== Command

Inheritance path = <<Control,Control>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

A Command is a discrete control used for supervisory control.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|normalValue
|1..1
|<<Integer,Integer>>
|
Normal value for Control.value e.g. used for percentage scaling.


|value
|1..1
|<<Integer,Integer>>
|
The value representing the actuator output.


|DiscreteValue
|1..1
|<<DiscreteValue,DiscreteValue>>
|
The MeasurementValue that is controlled.


|ValueAliasSet
|0..1
|<<ValueAliasSet,ValueAliasSet>>
|
The ValueAliasSet used for translation of a Control value to a name.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlType
|1..1
|string
|see <<Control,Control>>

|operationInProgress
|0..1
|boolean
|see <<Control,Control>>

|timeStamp
|0..1
|dateTime
|see <<Control,Control>>

|unitMultiplier (enumeration)
|0..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Control,Control>>

|unitSymbol (enumeration)
|0..1
|<<UnitSymbol,UnitSymbol>>
|see <<Control,Control>>

|PowerSystemResource
|0..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Control,Control>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Discrete]
==== Discrete

Inheritance path = <<Measurement,Measurement>> => <<IdentifiedObject,IdentifiedObject>>

Discrete represents a discrete Measurement, i.e. a Measurement representing discrete values, e.g. a Breaker position.

The association to Terminal may not be required depending on how the Measurement is being used. See section Use of Measurement Class for details.

The measurementType attribute is used to define the quantity being measured (Voltage, ThreePhaseActivePower, etc.) by a Measurement. The valid values for the measurementType are defined in Normative String Tables.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|ValueAliasSet
|0..1
|<<ValueAliasSet,ValueAliasSet>>
|
The ValueAliasSet used for translation of a MeasurementValue.value to a name.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|measurementType
|1..1
|string
|see <<Measurement,Measurement>>

|phases (enumeration)
|0..1
|<<PhaseCode,PhaseCode>>
|see <<Measurement,Measurement>>

|unitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Measurement,Measurement>>

|unitSymbol (enumeration)
|1..1
|<<UnitSymbol,UnitSymbol>>
|see <<Measurement,Measurement>>

|PowerSystemResource
|1..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Measurement,Measurement>>

|Terminal
|0..1
|<<ACDCTerminal,ACDCTerminal>>
|see <<Measurement,Measurement>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#DiscreteValue]
==== DiscreteValue

Inheritance path = <<MeasurementValue,MeasurementValue>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

DiscreteValue represents a discrete MeasurementValue.

- In the context of this profile this class is only used to define measurements that are available via ICCP. It is not used to supply values for those measurements. Consequently the value attribute is not included in this profile.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|Discrete
|1..1
|<<Discrete,Discrete>>
|
Measurement to which this value is connected.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|sensorAccuracy
|0..1
|<<PerCent,PerCent>>
|see <<MeasurementValue,MeasurementValue>>

|timeStamp
|0..1
|dateTime
|see <<MeasurementValue,MeasurementValue>>

|MeasurementValueSource
|1..1
|<<MeasurementValueSource,MeasurementValueSource>>
|see <<MeasurementValue,MeasurementValue>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#MeasurementValueQuality]
==== MeasurementValueQuality

Inheritance path = <<Quality61850,Quality61850>>

Measurement quality flags. Bits 0-10 are defined for substation automation in IEC 61850-7-3. Bits 11-15 are reserved for future expansion by that document. Bits 16-31 are reserved for EMS applications.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|MeasurementValue
|1..1
|<<MeasurementValue,MeasurementValue>>
|
A MeasurementValue has a MeasurementValueQuality associated with it.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|badReference
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|estimatorReplaced
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|failure
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|oldData
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|operatorBlocked
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|oscillatory
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|outOfRange
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|overFlow
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|source (enumeration)
|0..1
|<<Source,Source>>
|see <<Quality61850,Quality61850>>

|suspect
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|test
|0..1
|boolean
|see <<Quality61850,Quality61850>>

|validity (enumeration)
|0..1
|<<Validity,Validity>>
|see <<Quality61850,Quality61850>>
|===

[#MeasurementValueSource]
==== MeasurementValueSource

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

MeasurementValueSource describes the alternative sources updating a MeasurementValue. User conventions for how to use the MeasurementValueSource attributes are defined in IEC 61970-301.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RaiseLowerCommand]
==== RaiseLowerCommand

Inheritance path = <<AnalogControl,AnalogControl>> => <<Control,Control>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

An analog control that increases or decreases a set point value with pulses. Unless otherwise specified, one pulse moves the set point by one.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|ValueAliasSet
|0..1
|<<ValueAliasSet,ValueAliasSet>>
|
The ValueAliasSet used for translation of a Control value to a name.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|maxValue
|1..1
|float
|see <<AnalogControl,AnalogControl>>

|minValue
|1..1
|float
|see <<AnalogControl,AnalogControl>>

|AnalogValue
|1..1
|<<AnalogValue,AnalogValue>>
|see <<AnalogControl,AnalogControl>>

|controlType
|1..1
|string
|see <<Control,Control>>

|operationInProgress
|0..1
|boolean
|see <<Control,Control>>

|timeStamp
|0..1
|dateTime
|see <<Control,Control>>

|unitMultiplier (enumeration)
|0..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Control,Control>>

|unitSymbol (enumeration)
|0..1
|<<UnitSymbol,UnitSymbol>>
|see <<Control,Control>>

|PowerSystemResource
|0..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Control,Control>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#SetPoint]
==== SetPoint

Inheritance path = <<AnalogControl,AnalogControl>> => <<Control,Control>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

An analog control that issues a set point value.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|normalValue
|1..1
|<<Float,Float>>
|
Normal value for Control.value e.g. used for percentage scaling.


|value
|1..1
|<<Float,Float>>
|
The value representing the actuator output.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|maxValue
|1..1
|float
|see <<AnalogControl,AnalogControl>>

|minValue
|1..1
|float
|see <<AnalogControl,AnalogControl>>

|AnalogValue
|1..1
|<<AnalogValue,AnalogValue>>
|see <<AnalogControl,AnalogControl>>

|controlType
|1..1
|string
|see <<Control,Control>>

|operationInProgress
|0..1
|boolean
|see <<Control,Control>>

|timeStamp
|0..1
|dateTime
|see <<Control,Control>>

|unitMultiplier (enumeration)
|0..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Control,Control>>

|unitSymbol (enumeration)
|0..1
|<<UnitSymbol,UnitSymbol>>
|see <<Control,Control>>

|PowerSystemResource
|0..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Control,Control>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#StringMeasurement]
==== StringMeasurement

Inheritance path = <<Measurement,Measurement>> => <<IdentifiedObject,IdentifiedObject>>

StringMeasurement represents a measurement with values of type string.

The association to Terminal may not be required depending on how the Measurement is being used. See section Use of Measurement Class for details.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|measurementType
|1..1
|string
|see <<Measurement,Measurement>>

|phases (enumeration)
|0..1
|<<PhaseCode,PhaseCode>>
|see <<Measurement,Measurement>>

|unitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Measurement,Measurement>>

|unitSymbol (enumeration)
|1..1
|<<UnitSymbol,UnitSymbol>>
|see <<Measurement,Measurement>>

|PowerSystemResource
|1..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Measurement,Measurement>>

|Terminal
|0..1
|<<ACDCTerminal,ACDCTerminal>>
|see <<Measurement,Measurement>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#StringMeasurementValue]
==== StringMeasurementValue

Inheritance path = <<MeasurementValue,MeasurementValue>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

StringMeasurementValue represents a measurement value of type string.

In the context of this profile this class is only used to define measurements that are available via ICCP. It is not used to supply values for those measurements. Consequently the value attribute is not included in this profile.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|StringMeasurement
|1..1
|<<StringMeasurement,StringMeasurement>>
|
Measurement to which this value is connected.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|sensorAccuracy
|0..1
|<<PerCent,PerCent>>
|see <<MeasurementValue,MeasurementValue>>

|timeStamp
|0..1
|dateTime
|see <<MeasurementValue,MeasurementValue>>

|MeasurementValueSource
|1..1
|<<MeasurementValueSource,MeasurementValueSource>>
|see <<MeasurementValue,MeasurementValue>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ValueAliasSet]
==== ValueAliasSet

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

Describes the translation of a set of values into a name and is intendend to facilitate custom translations. Each ValueAliasSet has a name, description etc. A specific Measurement may represent a discrete state like Open, Closed, Intermediate etc. This requires a translation from the MeasurementValue.value number to a string, e.g. 0-&gt;"Invalid", 1-&gt;"Open", 2-&gt;"Closed", 3-&gt;"Intermediate". Each ValueToAlias member in ValueAliasSet.Value describe a mapping for one particular value to a name.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ValueToAlias]
==== ValueToAlias

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

Describes the translation of one particular value into a name, e.g. 1 as "Open".


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<Integer,Integer>>
|
The value that is mapped.


|ValueAliasSet
|1..1
|<<ValueAliasSet,ValueAliasSet>>
|
The ValueAliasSet having the ValueToAlias mappings.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===


=== Abstract Classes

[#ACDCTerminal]
==== ACDCTerminal

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

An electrical connection point (AC or DC) to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AnalogControl]
==== AnalogControl

Inheritance path = <<Control,Control>> => <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

An analog control used for supervisory control.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|maxValue
|1..1
|<<Float,Float>>
|
Normal value range maximum for any of the Control.value. Used for scaling, e.g. in bar graphs.


|minValue
|1..1
|<<Float,Float>>
|
Normal value range minimum for any of the Control.value. Used for scaling, e.g. in bar graphs.


|AnalogValue
|1..1
|<<AnalogValue,AnalogValue>>
|
The MeasurementValue that is controlled.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlType
|1..1
|string
|see <<Control,Control>>

|operationInProgress
|0..1
|boolean
|see <<Control,Control>>

|timeStamp
|0..1
|dateTime
|see <<Control,Control>>

|unitMultiplier (enumeration)
|0..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<Control,Control>>

|unitSymbol (enumeration)
|0..1
|<<UnitSymbol,UnitSymbol>>
|see <<Control,Control>>

|PowerSystemResource
|0..1
|<<PowerSystemResource,PowerSystemResource>>
|see <<Control,Control>>

|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Control]
==== Control

Inheritance path = <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

Control is used for supervisory/device control. It represents control outputs that are used to change the state in a process, e.g. close or open breaker, a set point value or a raise lower command.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|controlType
|1..1
|<<String,String>>
|
Specifies the type of Control. For example, this specifies if the Control represents BreakerOpen, BreakerClose, GeneratorVoltageSetPoint, GeneratorRaise, GeneratorLower, etc.


|operationInProgress
|0..1
|<<Boolean,Boolean>>
|
Indicates that a client is currently sending control commands that has not completed.


|timeStamp
|0..1
|<<DateTime,DateTime>>
|
The last time a control output was sent.


|unitMultiplier (enumeration)
|0..1
|<<UnitMultiplier,UnitMultiplier>>
|
The unit multiplier of the controlled quantity.


|unitSymbol (enumeration)
|0..1
|<<UnitSymbol,UnitSymbol>>
|
The unit of measure of the controlled quantity.


|PowerSystemResource
|0..1
|<<PowerSystemResource,PowerSystemResource>>
|
Regulating device governed by this control output.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#IOPoint]
==== IOPoint

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

The class describe a measurement or control value. The purpose is to enable having attributes and associations common for measurement and control.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#IdentifiedObject]
==== IdentifiedObject


This is a root class to provide common identification for all classes needing identification and naming attributes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|mRID
|1..1
|<<String,String>>
|
Master resource identifier issued by a model authority. The mRID is unique within an exchange context. Global uniqueness is easily achieved by using a UUID, as specified in RFC 4122, for the mRID. The use of UUID is strongly recommended.

For CIMXML data files in RDF syntax conforming to IEC 61970-552, the mRID is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.


|description
|0..1
|<<String,String>>
|
The description is a free human readable text describing or naming the object. It may be non unique and may not correlate to a naming hierarchy.


|name
|1..1
|<<String,String>>
|
The name is any free human readable and possibly non unique text naming the object.

|===

[#Limit]
==== Limit

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

Specifies one limit value for a Measurement. A Measurement typically has several limits that are kept together by the LimitSet class. The actual meaning and use of a Limit instance (i.e., if it is an alarm or warning limit or if it is a high or low limit) is not captured in the Limit class. However the name of a Limit instance may indicate both meaning and use.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#LimitSet]
==== LimitSet

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

Specifies a set of Limits that are associated with a Measurement. A Measurement may have several LimitSets corresponding to seasonal or other changing conditions. The condition is captured in the name and description attributes. The same LimitSet may be used for several Measurements. In particular percentage limits are used this way.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|isPercentageLimits
|0..1
|<<Boolean,Boolean>>
|
Tells if the limit values are in percentage of normalValue or the specified Unit for Measurements and Controls.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Measurement]
==== Measurement

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

A Measurement represents any measured, calculated or non-measured non-calculated quantity. Any piece of equipment may contain Measurements, e.g. a substation may have temperature measurements and door open indications, a transformer may have oil temperature and tank pressure measurements, a bay may contain a number of power flow measurements and a Breaker may contain a switch status measurement.

The PSR - Measurement association is intended to capture this use of Measurement and is included in the naming hierarchy based on EquipmentContainer. The naming hierarchy typically has Measurements as leaves, e.g. Substation-VoltageLevel-Bay-Switch-Measurement.

Some Measurements represent quantities related to a particular sensor location in the network, e.g. a voltage transformer (VT) or potential transformer (PT) at a busbar or a current transformer (CT) at the bar between a breaker and an isolator. The sensing position is not captured in the PSR - Measurement association. Instead it is captured by the Measurement - Terminal association that is used to define the sensing location in the network topology. The location is defined by the connection of the Terminal to ConductingEquipment.

If both a Terminal and PSR are associated, and the PSR is of type ConductingEquipment, the associated Terminal should belong to that ConductingEquipment instance.

When the sensor location is needed both Measurement-PSR and Measurement-Terminal are used. The Measurement-Terminal association is never used alone.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|measurementType
|1..1
|<<String,String>>
|
Specifies the type of measurement. For example, this specifies if the measurement represents an indoor temperature, outdoor temperature, bus voltage, line flow, etc.

When the measurementType is set to "Specialization", the type of Measurement is defined in more detail by the specialized class which inherits from Measurement.


|phases (enumeration)
|0..1
|<<PhaseCode,PhaseCode>>
|
Indicates to which phases the measurement applies and avoids the need to use 'measurementType' to also encode phase information (which would explode the types). The phase information in Measurement, along with 'measurementType' and 'phases' uniquely defines a Measurement for a device, based on normal network phase. Their meaning will not change when the computed energizing phasing is changed due to jumpers or other reasons.

If the attribute is missing three phases (ABC) shall be assumed.


|unitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|
The unit multiplier of the measured quantity.


|unitSymbol (enumeration)
|1..1
|<<UnitSymbol,UnitSymbol>>
|
The unit of measure of the measured quantity.


|PowerSystemResource
|1..1
|<<PowerSystemResource,PowerSystemResource>>
|
The power system resource that contains the measurement.


|Terminal
|0..1
|<<ACDCTerminal,ACDCTerminal>>
|
One or more measurements may be associated with a terminal in the network.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#MeasurementValue]
==== MeasurementValue

Inheritance path = <<IOPoint,IOPoint>> => <<IdentifiedObject,IdentifiedObject>>

The current state for a measurement. A state value is an instance of a measurement from a specific source. Measurements can be associated with many state values, each representing a different source for the measurement.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|sensorAccuracy
|0..1
|<<PerCent,PerCent>>
|
The limit, expressed as a percentage of the sensor maximum, that errors will not exceed when the sensor is used under reference conditions.


|timeStamp
|0..1
|<<DateTime,DateTime>>
|
The time when the value was last updated.


|MeasurementValueSource
|1..1
|<<MeasurementValueSource,MeasurementValueSource>>
|
A reference to the type of source that updates the MeasurementValue, e.g. SCADA, CCLink, manual, etc. User conventions for the names of sources are contained in the introduction to IEC 61970-301.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PowerSystemResource]
==== PowerSystemResource

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

A power system resource (PSR) can be an item of equipment such as a switch, an equipment container containing many individual items of equipment such as a substation, or an organisational entity such as sub-control area. Power system resources can have measurements associated.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Quality61850]
==== Quality61850


Quality flags in this class are as defined in IEC 61850, except for estimatorReplaced, which has been included in this class for convenience.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|badReference
|0..1
|<<Boolean,Boolean>>
|
Measurement value may be incorrect due to a reference being out of calibration.


|estimatorReplaced
|0..1
|<<Boolean,Boolean>>
|
Value has been replaced by State Estimator. estimatorReplaced is not an IEC61850 quality bit but has been put in this class for convenience.


|failure
|0..1
|<<Boolean,Boolean>>
|
This identifier indicates that a supervision function has detected an internal or external failure, e.g. communication failure.


|oldData
|0..1
|<<Boolean,Boolean>>
|
Measurement value is old and possibly invalid, as it has not been successfully updated during a specified time interval.


|operatorBlocked
|0..1
|<<Boolean,Boolean>>
|
Measurement value is blocked and hence unavailable for transmission.


|oscillatory
|0..1
|<<Boolean,Boolean>>
|
To prevent some overload of the communication it is sensible to detect and suppress oscillating (fast changing) binary inputs. If a signal changes in a defined time twice in the same direction (from 0 to 1 or from 1 to 0) then oscillation is detected and the detail quality identifier "oscillatory" is set. If it is detected a configured numbers of transient changes could be passed by. In this time the validity status "questionable" is set. If after this defined numbers of changes the signal is still in the oscillating state the value shall be set either to the opposite state of the previous stable value or to a defined default value. In this case the validity status "questionable" is reset and "invalid" is set as long as the signal is oscillating. If it is configured such that no transient changes should be passed by then the validity status "invalid" is set immediately in addition to the detail quality identifier "oscillatory" (used for status information only).


|outOfRange
|0..1
|<<Boolean,Boolean>>
|
Measurement value is beyond a predefined range of value.


|overFlow
|0..1
|<<Boolean,Boolean>>
|
Measurement value is beyond the capability of being represented properly. For example, a counter value overflows from maximum count back to a value of zero.


|source (enumeration)
|0..1
|<<Source,Source>>
|
Source gives information related to the origin of a value. The value may be acquired from the process, defaulted or substituted.


|suspect
|0..1
|<<Boolean,Boolean>>
|
A correlation function has detected that the value is not consistent with other values. Typically set by a network State Estimator.


|test
|0..1
|<<Boolean,Boolean>>
|
Measurement value is transmitted for test purposes.


|validity (enumeration)
|0..1
|<<Validity,Validity>>
|
Validity of the measurement value.

|===

[#Terminal]
==== Terminal

Inheritance path = <<ACDCTerminal,ACDCTerminal>> => <<IdentifiedObject,IdentifiedObject>>

An AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|description
|0..1
|string
|see <<IdentifiedObject,IdentifiedObject>>

|name
|1..1
|string
|see <<IdentifiedObject,IdentifiedObject>>
|===



=== Enumerations

[#PhaseCode]
==== PhaseCode

An unordered enumeration of phase identifiers. Allows designation of phases for both transmission and distribution equipment, circuits and loads. The enumeration, by itself, does not describe how the phases are connected together or connected to ground. Ground is not explicitly denoted as a phase.

Residential and small commercial loads are often served from single-phase, or split-phase, secondary circuits. For the example of s12N, phases 1 and 2 refer to hot wires that are 180 degrees out of phase, while N refers to the neutral wire. Through single-phase transformer connections, these secondary circuits may be served from one or two of the primary phases A, B, and C. For three-phase loads, use the A, B, C phase codes instead of s12N.

The integer values are from IEC 61968-9 to support revenue metering applications.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|A
|
Phase A.


|AB
|
Phases A and B.


|ABC
|
Phases A, B, and C.


|ABCN
|
Phases A, B, C, and N.


|ABN
|
Phases A, B, and neutral.


|AC
|
Phases A and C.


|ACN
|
Phases A, C and neutral.


|AN
|
Phases A and neutral.


|B
|
Phase B.


|BC
|
Phases B and C.


|BCN
|
Phases B, C, and neutral.


|BN
|
Phases B and neutral.


|C
|
Phase C.


|CN
|
Phases C and neutral.


|N
|
Neutral phase.


|X
|
Unknown non-neutral phase.


|XN
|
Unknown non-neutral phase plus neutral.


|XY
|
Two unknown non-neutral phases.


|XYN
|
Two unknown non-neutral phases plus neutral.


|none
|
No phases specified.


|s1
|
Secondary phase 1.


|s12
|
Secondary phase 1 and 2.


|s12N
|
Secondary phases 1, 2, and neutral.


|s1N
|
Secondary phase 1 and neutral.


|s2
|
Secondary phase 2.


|s2N
|
Secondary phase 2 and neutral.

|===
[#Source]
==== Source

Source gives information related to the origin of a value.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|DEFAULTED
|
The value contains a default value.


|PROCESS
|
The value is provided by input from the process I/O or being calculated from some function.


|SUBSTITUTED
|
The value is provided by input of an operator or by an automatic source.

|===
[#UnitMultiplier]
==== UnitMultiplier

The unit multipliers defined for the CIM. When applied to unit symbols, the unit symbol is treated as a derived unit. Regardless of the contents of the unit symbol text, the unit symbol shall be treated as if it were a single-character unit symbol. Unit symbols should not contain multipliers, and it should be left to the multiplier to define the multiple for an entire data type.

For example, if a unit symbol is "m2Pers" and the multiplier is "k", then the value is k(m**2/s), and the multiplier applies to the entire final value, not to any individual part of the value. This can be conceptualized by substituting a derived unit symbol for the unit type. If one imagines that the symbol "" represents the derived unit "m2Pers", then applying the multiplier "k" can be conceptualized simply as "k".

For example, the SI unit for mass is "kg" and not "g". If the unit symbol is defined as "kg", then the multiplier is applied to "kg" as a whole and does not replace the "k" in front of the "g". In this case, the multiplier of "m" would be used with the unit symbol of "kg" to represent one gram. As a text string, this violates the instructions in IEC 80000-1. However, because the unit symbol in CIM is treated as a derived unit instead of as an SI unit, it makes more sense to conceptualize the "kg" as if it were replaced by one of the proposed replacements for the SI mass symbol. If one imagines that the "kg" were replaced by a symbol "", then it is easier to conceptualize the multiplier "m" as creating the proper unit "m", and not the forbidden unit "mkg".


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|G
|
Giga 10**9.


|M
|
Mega 10**6.


|T
|
Tera 10**12.


|c
|
Centi 10**-2.


|d
|
Deci 10**-1.


|k
|
Kilo 10**3.


|m
|
Milli 10**-3.


|micro
|
Micro 10**-6.


|n
|
Nano 10**-9.


|none
|
No multiplier or equivalently multiply by 1.


|p
|
Pico 10**-12.

|===
[#UnitSymbol]
==== UnitSymbol

The derived units defined for usage in the CIM. In some cases, the derived unit is equal to an SI unit. Whenever possible, the standard derived symbol is used instead of the formula for the derived unit. For example, the unit symbol Farad is defined as "F" instead of "CPerV". In cases where a standard symbol does not exist for a derived unit, the formula for the unit is used as the unit symbol. For example, density does not have a standard symbol and so it is represented as "kgPerm3". With the exception of the "kg", which is an SI unit, the unit symbols do not contain multipliers and therefore represent the base derived unit to which a multiplier can be applied as a whole.

Every unit symbol is treated as an unparseable text as if it were a single-letter symbol. The meaning of each unit symbol is defined by the accompanying descriptive text and not by the text contents of the unit symbol.

To allow the widest possible range of serializations without requiring special character handling, several substitutions are made which deviate from the format described in IEC 80000-1. The division symbol "/" is replaced by the letters "Per". Exponents are written in plain text after the unit as "m3" instead of being formatted as "m" with a superscript of 3 or introducing a symbol as in "m^3". The degree symbol "" is replaced with the letters "deg". Any clarification of the meaning for a substitution is included in the description for the unit symbol.

Non-SI units are included in list of unit symbols to allow sources of data to be correctly labelled with their non-SI units (for example, a GPS sensor that is reporting numbers that represent feet instead of meters). This allows software to use the unit symbol information correctly convert and scale the raw data of those sources into SI-based units.

The integer values are used for harmonization with IEC 61850.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|A
|
Current in amperes.


|F
|
Electric capacitance in farads (C/V).


|H
|
Electric inductance in henrys (Wb/A).


|Hz
|
Frequency in hertz (1/s).


|J
|
Energy in joules (Nm = CV = Ws).


|N
|
Force in newtons (kgm/s).


|Pa
|
Pressure in pascals (N/m). Note: the absolute or relative measurement of pressure is implied with this entry. See below for more explicit forms.


|S
|
Conductance in siemens.


|V
|
Electric potential in volts (W/A).


|VA
|
Apparent power in volt amperes. See also real power and reactive power.


|VAh
|
Apparent energy in volt ampere hours.


|VAr
|
Reactive power in volt amperes reactive. The reactive or imaginary component of electrical power (VIsin(phi)). (See also real power and apparent power).

Note: Different meter designs use different methods to arrive at their results. Some meters may compute reactive power as an arithmetic value, while others compute the value vectorially. The data consumer should determine the method in use and the suitability of the measurement for the intended purpose.


|VArh
|
Reactive energy in volt ampere reactive hours.


|W
|
Real power in watts (J/s). Electrical power may have real and reactive components. The real portion of electrical power (I&#178;R or VIcos(phi)), is expressed in Watts. See also apparent power and reactive power.


|Wh
|
Real energy in watt hours.


|deg
|
Plane angle in degrees.


|degC
|
Relative temperature in degrees Celsius.

In the SI unit system the symbol is C. Electric charge is measured in coulomb that has the unit symbol C. To distinguish degree Celsius from coulomb the symbol used in the UML is degC. The reason for not using C is that the special character is difficult to manage in software.


|g
|

|h
|
Time in hours, hour = 60 min = 3600 s.


|m
|
Length in metres.


|m2
|
Area in square metres (m).


|m3
|
Volume in cubic metres (m).


|min
|
Time in minutes, minute = 60 s.


|none
|
Dimension less quantity, e.g. count, per unit, etc.


|ohm
|
Electric resistance in ohms (V/A).


|rad
|
Plane angle in radians (m/m).


|s
|
Time in seconds.

|===
[#Validity]
==== Validity

Validity for MeasurementValue.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|GOOD
|
The value is marked good if no abnormal condition of the acquisition function or the information source is detected.


|INVALID
|
The value is marked invalid when a supervision function recognises abnormal conditions of the acquisition function or the information source (missing or non-operating updating devices). The value is not defined under this condition. The mark invalid is used to indicate to the client that the value may be incorrect and shall not be used.


|QUESTIONABLE
|
The value is marked questionable if a supervision function detects an abnormal behaviour, however the value could still be valid. The client is responsible for determining whether or not values marked "questionable" should be used.

|===

=== Datatypes

[#PerCent]
==== PerCent

Percentage on a defined base. For example, specify as 100 to indicate at the defined base.


XSD type: float


=== Primitive Types

[#CGMES-Operation-Boolean]
==== Boolean

A type with the value space "true" and "false".


XSD type: boolean

[#CGMES-Operation-DateTime]
==== DateTime

Date and time as "yyyy-mm-ddThh:mm:ss.sss", which conforms with ISO 8601. UTC time zone is specified as "yyyy-mm-ddThh:mm:ss.sssZ". A local timezone relative UTC is specified as "yyyy-mm-ddThh:mm:ss.sss-hh:mm". The second component (shown here as "ss.sss") could have any number of digits in its fractional part to allow any kind of precision beyond seconds.


XSD type: dateTime

[#CGMES-Operation-Float]
==== Float

A floating point number. The range is unspecified and not limited.


XSD type: float

[#CGMES-Operation-Integer]
==== Integer

An integer number. The range is unspecified and not limited.


XSD type: integer

[#CGMES-Operation-String]
==== String

A string consisting of a sequence of characters. The character encoding is UTF-8. The string length is unspecified and unlimited.


XSD type: string

