@startuml
top to bottom direction
hide empty methods


skinparam BackgroundColor #FFFFFF
skinparam shadowing false
skinparam RoundCorner 5
skinparam BorderColor #454645
skinparam ArrowColor #454645
skinparam FontColor #000000

skinparam class {
  ' Concrete classes style definition
  BackgroundColor #FFFFE0
  FontColor #000000
  AttributeFontColor #000000
  StereotypeFontColor #000000
  HeaderFontColor #000000
  BorderColor #454645
  BorderThickness 1
  
  ' Abstract classes style definition
  BackgroundColor<<abstract>> #D3D3D3
  FontColor<<abstract>> #000000
  AttributeFontColor<<abstract>> #000000
  StereotypeFontColor<<abstract>> #000000
  HeaderFontColor<<abstract>> #000000
  BorderColor<<abstract>> #454645
  BorderThickness<<abstract>> 1
  
  ' Enumerations style definition
  BackgroundColor<<enumeration>> #90EE90
  FontColor<<enumeration>> #000000
  AttributeFontColor<<enumeration>> #000000
  StereotypeFontColor<<enumeration>> #000000
  HeaderFontColor <<enumeration>> #000000
  BorderColor<<enumeration>> #454645
  BorderThickness<<enumeration>> 1
  
  ' CIMDatatypes style definition
  BackgroundColor<<CIMDatatype>> #FFEBCD
  FontColor<<CIMDatatype>> #000000
  AttributeFontColor<<CIMDatatype>> #000000
  StereotypeFontColor<<CIMDatatype>> #000000
  HeaderFontColor<<CIMDatatype>> #000000
  BorderColor<<CIMDatatype>> #454645
  BorderThickness<<CIMDatatype>> 1
  
  ' Compound classes style definition
  BackgroundColor<<Compound>> #FFEBCD
  FontColor<<Compound>> #000000
  AttributeFontColor<<Compound>> #000000
  StereotypeFontColor<<Compound>> #000000
  HeaderFontColor<<Compound>> #000000
  BorderColor<<Compound>> #454645
  BorderThickness<<Compound>> 1
  
  ' Primitive classes style definition
  BackgroundColor<<Primitive>> #E6E6FF
  FontColor<<Primitive>> #000000
  AttributeFontColor<<Primitive>> #000000
  StereotypeFontColor<<Primitive>> #000000
  HeaderFontColor<<Primitive>> #000000
  BorderColor<<Primitive>> #454645
  BorderThickness<<Primitive>> 1
  
  ' Errors classes style definition
  BackgroundColor<<error>> #FFC0CB
  FontColor<<error>> #000000
  AttributeFontColor<<error>> #000000
  StereotypeFontColor<<error>> #000000
  HeaderFontColor<<error>> #000000
  BorderColor<<error>> #454645
  BorderThickness<<error>> 1
}
skinparam shadowing true

hide <<abstract>> stereotype
hide <<error>> stereotype


skinparam note {
  BorderColor #454645
  BorderThickness 1.5
  FontSize 14
  Font Bold
  FontColor #000000
}
' Add a note towards the upper left corner of the diagram
note as OperationNote #lightyellow
   Profile: Operation
   Namespace: http://iec.ch/TC57/ns/CIM/Operation-EU/3.0#
   
   Profile Notes:
      This profile represents the equipment of the power system and their hierarchical
      relationships.
      
end note

' ACDCTerminal inherits from IdentifiedObject
abstract class ACDCTerminal  <<abstract>> {
}

IdentifiedObject <|-- ACDCTerminal

' Accumulator inherits from Measurement
class Accumulator   {
}

Measurement <|-- Accumulator

' AccumulatorLimit inherits from Limit
class AccumulatorLimit   {
   +value : integer [1]
}

Limit <|-- AccumulatorLimit
AccumulatorLimit "+Limits 0..*" --> "+LimitSet 1" AccumulatorLimitSet

' AccumulatorLimitSet inherits from LimitSet
class AccumulatorLimitSet   {
}

LimitSet <|-- AccumulatorLimitSet
AccumulatorLimitSet "+LimitSets 0..*" --> "+Measurements 1..*" Accumulator

' AccumulatorReset inherits from Control
class AccumulatorReset   {
}

Control <|-- AccumulatorReset
AccumulatorReset "+AccumulatorReset 0..1" --> "+AccumulatorValue 1" AccumulatorValue

' AccumulatorValue inherits from MeasurementValue
class AccumulatorValue   {
}

MeasurementValue <|-- AccumulatorValue
AccumulatorValue "+AccumulatorValues 0..*" --> "+Accumulator 1" Accumulator

' Analog inherits from Measurement
class Analog   {
   +positiveFlowIn : boolean [0..1]
}

Measurement <|-- Analog

' AnalogControl inherits from Control
abstract class AnalogControl  <<abstract>> {
   +maxValue : float [1]
   +minValue : float [1]
}

Control <|-- AnalogControl
AnalogControl "+AnalogControl 0..1" --> "+AnalogValue 1" AnalogValue

' AnalogLimit inherits from Limit
class AnalogLimit   {
   +value : float [1]
}

Limit <|-- AnalogLimit
AnalogLimit "+Limits 0..*" --> "+LimitSet 1" AnalogLimitSet

' AnalogLimitSet inherits from LimitSet
class AnalogLimitSet   {
}

LimitSet <|-- AnalogLimitSet
AnalogLimitSet "+LimitSets 0..*" --> "+Measurements 1..*" Analog

' AnalogValue inherits from MeasurementValue
class AnalogValue   {
}

MeasurementValue <|-- AnalogValue
AnalogValue "+AnalogValues 0..*" --> "+Analog 1" Analog

' Command inherits from Control
class Command   {
   +normalValue : integer [1]
   +value : integer [1]
}

Control <|-- Command
Command "+Command 0..1" --> "+DiscreteValue 1" DiscreteValue
Command "+Commands 0..*" --> "+ValueAliasSet 0..1" ValueAliasSet

' Control inherits from IOPoint
abstract class Control  <<abstract>> {
   +controlType : string [1]
   +operationInProgress : boolean [0..1]
   +timeStamp : dateTime [0..1]
   +unitMultiplier : UnitMultiplier [0..1]
   +unitSymbol : UnitSymbol [0..1]
}

IOPoint <|-- Control
Control "+Controls 0..*" --> "+PowerSystemResource 0..1" PowerSystemResource

' Discrete inherits from Measurement
class Discrete   {
}

Measurement <|-- Discrete
Discrete "+Discretes 0..*" --> "+ValueAliasSet 0..1" ValueAliasSet

' DiscreteValue inherits from MeasurementValue
class DiscreteValue   {
}

MeasurementValue <|-- DiscreteValue
DiscreteValue "+DiscreteValues 0..*" --> "+Discrete 1" Discrete

' IOPoint inherits from IdentifiedObject
abstract class IOPoint  <<abstract>> {
}

IdentifiedObject <|-- IOPoint

' IdentifiedObject
abstract class IdentifiedObject  <<abstract>> {
   +mRID : string [1]
   +description : string [0..1]
   +name : string [1]
}


' Limit inherits from IdentifiedObject
abstract class Limit  <<abstract>> {
}

IdentifiedObject <|-- Limit

' LimitSet inherits from IdentifiedObject
abstract class LimitSet  <<abstract>> {
   +isPercentageLimits : boolean [0..1]
}

IdentifiedObject <|-- LimitSet

' Measurement inherits from IdentifiedObject
abstract class Measurement  <<abstract>> {
   +measurementType : string [1]
   +phases : PhaseCode [0..1]
   +unitMultiplier : UnitMultiplier [1]
   +unitSymbol : UnitSymbol [1]
}

IdentifiedObject <|-- Measurement
Measurement "+Measurements 0..*" --> "+PowerSystemResource 1" PowerSystemResource
Measurement "+Measurements 0..*" --> "+Terminal 0..1" ACDCTerminal

' MeasurementValue inherits from IOPoint
abstract class MeasurementValue  <<abstract>> {
   +sensorAccuracy : PerCent [0..1]
   +timeStamp : dateTime [0..1]
}

IOPoint <|-- MeasurementValue
MeasurementValue "+MeasurementValues 0..*" --> "+MeasurementValueSource 1" MeasurementValueSource

' MeasurementValueQuality inherits from Quality61850
class MeasurementValueQuality   {
}

Quality61850 <|-- MeasurementValueQuality
MeasurementValueQuality "+MeasurementValueQuality 0..1" --> "+MeasurementValue 1" MeasurementValue

' MeasurementValueSource inherits from IdentifiedObject
class MeasurementValueSource   {
}

IdentifiedObject <|-- MeasurementValueSource

' PowerSystemResource inherits from IdentifiedObject
abstract class PowerSystemResource  <<abstract>> {
}

IdentifiedObject <|-- PowerSystemResource

' Quality61850
abstract class Quality61850  <<abstract>> {
   +badReference : boolean [0..1]
   +estimatorReplaced : boolean [0..1]
   +failure : boolean [0..1]
   +oldData : boolean [0..1]
   +operatorBlocked : boolean [0..1]
   +oscillatory : boolean [0..1]
   +outOfRange : boolean [0..1]
   +overFlow : boolean [0..1]
   +source : Source [0..1]
   +suspect : boolean [0..1]
   +test : boolean [0..1]
   +validity : Validity [0..1]
}


' RaiseLowerCommand inherits from AnalogControl
class RaiseLowerCommand   {
}

AnalogControl <|-- RaiseLowerCommand
RaiseLowerCommand "+RaiseLowerCommands 0..*" --> "+ValueAliasSet 0..1" ValueAliasSet

' SetPoint inherits from AnalogControl
class SetPoint   {
   +normalValue : float [1]
   +value : float [1]
}

AnalogControl <|-- SetPoint

' StringMeasurement inherits from Measurement
class StringMeasurement   {
}

Measurement <|-- StringMeasurement

' StringMeasurementValue inherits from MeasurementValue
class StringMeasurementValue   {
}

MeasurementValue <|-- StringMeasurementValue
StringMeasurementValue "+StringMeasurementValues 0..*" --> "+StringMeasurement 1" StringMeasurement

' Terminal inherits from ACDCTerminal
abstract class Terminal  <<abstract>> {
}

ACDCTerminal <|-- Terminal

' ValueAliasSet inherits from IdentifiedObject
class ValueAliasSet   {
}

IdentifiedObject <|-- ValueAliasSet

' ValueToAlias inherits from IdentifiedObject
class ValueToAlias   {
   +value : integer [1]
}

IdentifiedObject <|-- ValueToAlias
ValueToAlias "+Values 0..*" --> "+ValueAliasSet 1" ValueAliasSet

@enduml
