@startuml
top to bottom direction
hide empty methods


skinparam BackgroundColor #FFFFFF
skinparam shadowing false
skinparam RoundCorner 5
skinparam BorderColor #454645
skinparam ArrowColor #454645
skinparam FontColor #000000

skinparam class {
  ' Concrete classes style definition
  BackgroundColor #FFFFE0
  FontColor #000000
  AttributeFontColor #000000
  StereotypeFontColor #000000
  HeaderFontColor #000000
  BorderColor #454645
  BorderThickness 1
  
  ' Abstract classes style definition
  BackgroundColor<<abstract>> #D3D3D3
  FontColor<<abstract>> #000000
  AttributeFontColor<<abstract>> #000000
  StereotypeFontColor<<abstract>> #000000
  HeaderFontColor<<abstract>> #000000
  BorderColor<<abstract>> #454645
  BorderThickness<<abstract>> 1
  
  ' Enumerations style definition
  BackgroundColor<<enumeration>> #90EE90
  FontColor<<enumeration>> #000000
  AttributeFontColor<<enumeration>> #000000
  StereotypeFontColor<<enumeration>> #000000
  HeaderFontColor <<enumeration>> #000000
  BorderColor<<enumeration>> #454645
  BorderThickness<<enumeration>> 1
  
  ' CIMDatatypes style definition
  BackgroundColor<<CIMDatatype>> #FFEBCD
  FontColor<<CIMDatatype>> #000000
  AttributeFontColor<<CIMDatatype>> #000000
  StereotypeFontColor<<CIMDatatype>> #000000
  HeaderFontColor<<CIMDatatype>> #000000
  BorderColor<<CIMDatatype>> #454645
  BorderThickness<<CIMDatatype>> 1
  
  ' Compound classes style definition
  BackgroundColor<<Compound>> #FFEBCD
  FontColor<<Compound>> #000000
  AttributeFontColor<<Compound>> #000000
  StereotypeFontColor<<Compound>> #000000
  HeaderFontColor<<Compound>> #000000
  BorderColor<<Compound>> #454645
  BorderThickness<<Compound>> 1
  
  ' Primitive classes style definition
  BackgroundColor<<Primitive>> #E6E6FF
  FontColor<<Primitive>> #000000
  AttributeFontColor<<Primitive>> #000000
  StereotypeFontColor<<Primitive>> #000000
  HeaderFontColor<<Primitive>> #000000
  BorderColor<<Primitive>> #454645
  BorderThickness<<Primitive>> 1
  
  ' Errors classes style definition
  BackgroundColor<<error>> #FFC0CB
  FontColor<<error>> #000000
  AttributeFontColor<<error>> #000000
  StereotypeFontColor<<error>> #000000
  HeaderFontColor<<error>> #000000
  BorderColor<<error>> #454645
  BorderThickness<<error>> 1
}
skinparam shadowing true

hide <<abstract>> stereotype
hide <<error>> stereotype


skinparam note {
  BorderColor #454645
  BorderThickness 1.5
  FontSize 14
  Font Bold
  FontColor #000000
}
' Add a note towards the upper left corner of the diagram
note as StateVariablesNote #lightyellow
   Profile: StateVariables
   Namespace: http://iec.ch/TC57/ns/CIM/StateVariables-EU/3.0#
end note

' ACDCConverter inherits from ConductingEquipment
abstract class ACDCConverter  <<abstract>> {
   +idc : CurrentFlow [1]
   +poleLossP : ActivePower [1]
   +uc : Voltage [1]
   +udc : Voltage [1]
}

ConductingEquipment <|-- ACDCConverter

' ACDCTerminal inherits from IdentifiedObject
abstract class ACDCTerminal  <<abstract>> {
}

IdentifiedObject <|-- ACDCTerminal

' ConductingEquipment
abstract class ConductingEquipment  <<abstract>> {
}


' CsConverter inherits from ACDCConverter
class CsConverter <<Description>>  {
   +alpha : AngleDegrees [1]
   +gamma : AngleDegrees [1]
}

ACDCConverter <|-- CsConverter

' DCTopologicalIsland inherits from IdentifiedObject
class DCTopologicalIsland   {
}

IdentifiedObject <|-- DCTopologicalIsland
DCTopologicalIsland "+DCTopologicalIsland 0..1" o--> "+DCTopologicalNodes 1..*" DCTopologicalNode

' DCTopologicalNode inherits from IdentifiedObject
abstract class DCTopologicalNode  <<abstract>> {
}

IdentifiedObject <|-- DCTopologicalNode

' IdentifiedObject
abstract class IdentifiedObject  <<abstract>> {
   +mRID : string [1]
   +name : string [1]
}


' ShuntCompensator
abstract class ShuntCompensator  <<abstract>> {
}


' SvInjection
class SvInjection   {
   +pInjection : ActivePower [1]
   +qInjection : ReactivePower [0..1]
}

SvInjection "+SvInjection 0..*" --> "+TopologicalNode 1" TopologicalNode

' SvPowerFlow
class SvPowerFlow   {
   +p : ActivePower [1]
   +q : ReactivePower [1]
}

SvPowerFlow "+SvPowerFlow 0..*" --> "+Terminal 1" Terminal

' SvShuntCompensatorSections
class SvShuntCompensatorSections   {
   +sections : float [1]
}

SvShuntCompensatorSections "+SvShuntCompensatorSections 0..*" --> "+ShuntCompensator 1" ShuntCompensator

' SvStatus
class SvStatus   {
   +inService : boolean [1]
}

SvStatus "+SvStatus 0..*" --> "+ConductingEquipment 1" ConductingEquipment

' SvSwitch
class SvSwitch   {
   +open : boolean [1]
}

SvSwitch "+SvSwitch 0..*" --> "+Switch 1" Switch

' SvTapStep
class SvTapStep   {
   +position : float [1]
}

SvTapStep "+SvTapStep 0..1" --> "+TapChanger 1" TapChanger

' SvVoltage
class SvVoltage   {
   +angle : AngleDegrees [1]
   +v : Voltage [1]
}

SvVoltage "+SvVoltage 0..*" --> "+TopologicalNode 1" TopologicalNode

' Switch inherits from ConductingEquipment
abstract class Switch  <<abstract>> {
}

ConductingEquipment <|-- Switch

' TapChanger
abstract class TapChanger  <<abstract>> {
}


' Terminal inherits from ACDCTerminal
abstract class Terminal  <<abstract>> {
}

ACDCTerminal <|-- Terminal

' TopologicalIsland inherits from IdentifiedObject
class TopologicalIsland   {
}

IdentifiedObject <|-- TopologicalIsland
TopologicalIsland "+AngleRefTopologicalIsland 0..1" --> "+AngleRefTopologicalNode 1" TopologicalNode
TopologicalIsland "+TopologicalIsland 0..1" o--> "+TopologicalNodes 1..*" TopologicalNode

' TopologicalNode
abstract class TopologicalNode  <<abstract>> {
}


' VsConverter inherits from ACDCConverter
class VsConverter <<Description>>  {
   +delta : AngleDegrees [1]
   +uv : Voltage [1]
}

ACDCConverter <|-- VsConverter

@enduml
