:pdf-themesdir: {docdir}
:pdf-theme: adoc-article-rdfs

= SteadyStateHypothesis Profile

// Settings:
:doctype: article
:reproducible:
:icons: font
:sectnums:
:sectnumlevels: 4
:xrefstyle: short
:toclevels: 4
:toc-title: Table of Contents
:toc:
:toc-placement: preamble

== Overview

Profile namespace: http://iec.ch/TC57/ns/CIM/SteadyStateHypothesis-EU/3.0#

plantuml::./Profiles/CPSM-NA-SteadyStateHypothesis.rdfs-t2b.puml[format=svg, align=center, caption="Figure 1: ", title="SteadyStateHypothesis Profile"]

== Profile Specification




=== Concrete Classes

[#ACDCConverterDCTerminal]
==== (Description) ACDCConverterDCTerminal

Inheritance path = <<DCBaseTerminal,DCBaseTerminal>> => <<ACDCTerminal,ACDCTerminal>> => <<IdentifiedObject,IdentifiedObject>>

A DC electrical connection point at the AC/DC converter. The AC/DC converter is electrically connected also to the AC side. The AC connection is inherited from the AC conducting equipment in the same way as any other AC equipment. The AC/DC converter DC terminal is separate from generic DC terminal to restrict the connection with the AC side to AC/DC converter and so that no other DC conducting equipment can be connected to the AC side.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|connected
|1..1
|<<Boolean,Boolean>>
|see <<ACDCTerminal,ACDCTerminal>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ActivePowerLimit]
==== (Description) ActivePowerLimit

Inheritance path = <<OperationalLimit,OperationalLimit>> => <<IdentifiedObject,IdentifiedObject>>

Limit on active power flow.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<ActivePower,ActivePower>>
|
Value of active power limit. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ApparentPowerLimit]
==== (Description) ApparentPowerLimit

Inheritance path = <<OperationalLimit,OperationalLimit>> => <<IdentifiedObject,IdentifiedObject>>

Apparent power limit.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<ApparentPower,ApparentPower>>
|
The apparent power limit. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#AsynchronousMachine]
==== (Description) AsynchronousMachine

Inheritance path = <<RotatingMachine,RotatingMachine>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A rotating machine whose shaft rotates asynchronously with the electrical field. Also known as an induction machine with no external connection to the rotor windings, e.g. squirrel-cage induction machine.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|asynchronousMachineType (enumeration)
|1..1
|<<AsynchronousMachineKind,AsynchronousMachineKind>>
|
Indicates the type of Asynchronous Machine (motor or generator).

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<RotatingMachine,RotatingMachine>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<RotatingMachine,RotatingMachine>>

|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#BatteryUnit]
==== (Description) BatteryUnit

Inheritance path = <<PowerElectronicsUnit,PowerElectronicsUnit>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

An electrochemical energy storage device.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|batteryState (enumeration)
|1..1
|<<BatteryStateKind,BatteryStateKind>>
|
The current state of the battery (charging, full, etc.).


|storedE
|1..1
|<<RealEnergy,RealEnergy>>
|
Amount of energy currently stored. The attribute shall be a positive value or zero and lower than BatteryUnit.ratedE.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Breaker]
==== (Description) Breaker

Inheritance path = <<ProtectedSwitch,ProtectedSwitch>> => <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A mechanical switching device capable of making, carrying, and breaking currents under normal circuit conditions and also making, carrying for a specified time, and breaking currents under specified abnormal circuit conditions e.g. those of short circuit.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ConformLoad]
==== (Description) ConformLoad

Inheritance path = <<EnergyConsumer,EnergyConsumer>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

ConformLoad represent loads that follow a daily load change pattern where the pattern can be used to scale the load with a system load.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<EnergyConsumer,EnergyConsumer>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<EnergyConsumer,EnergyConsumer>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ControlArea]
==== (Description) ControlArea

Inheritance path = <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A control area is a grouping of generating units and/or loads and a cutset of tie lines (as terminals) which may be used for a variety of purposes including automatic generation control, power flow solution area interchange control specification, and input to load forecasting. All generation and load within the area defined by the terminals on the border are considered in the area interchange control. Note that any number of overlapping control area specifications can be superimposed on the physical model. The following general principles apply to ControlArea:

1. The control area orientation for net interchange is positive for an import, negative for an export.

2. The control area net interchange is determined by summing flows in Terminals. The Terminals are identified by creating a set of TieFlow objects associated with a ControlArea object. Each TieFlow object identifies one Terminal.

3. In a single network model, a tie between two control areas must be modelled in both control area specifications, such that the two representations of the tie flow sum to zero.

4. The normal orientation of Terminal flow is positive for flow into the conducting equipment that owns the Terminal. (i.e. flow from a bus into a device is positive.) However, the orientation of each flow in the control area specification must align with the control area convention, i.e. import is positive. If the orientation of the Terminal flow referenced by a TieFlow is positive into the control area, then this is confirmed by setting TieFlow.positiveFlowIn flag TRUE. If not, the orientation must be reversed by setting the TieFlow.positiveFlowIn flag FALSE.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|netInterchange
|1..1
|<<ActivePower,ActivePower>>
|
The specified positive net interchange into the control area, i.e. positive sign means flow into the area.


|pTolerance
|0..1
|<<ActivePower,ActivePower>>
|
Active power net interchange tolerance. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#CsConverter]
==== (Description) CsConverter

Inheritance path = <<ACDCConverter,ACDCConverter>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

DC side of the current source converter (CSC).

The firing angle controls the dc voltage at the converter, both for rectifier and inverter. The difference between the dc voltages of the rectifier and inverter determines the dc current. The extinction angle is used to limit the dc voltage at the inverter, if needed, and is not used in active power control. The firing angle, transformer tap position and number of connected filters are the primary means to control a current source dc line. Higher level controls are built on top, e.g. dc voltage, dc current and active power. From a steady state perspective it is sufficient to specify the wanted active power transfer (ACDCConverter.targetPpcc) and the control functions will set the dc voltage, dc current, firing angle, transformer tap position and number of connected filters to meet this. Therefore attributes targetAlpha and targetGamma are not applicable in this case.

The reactive power consumed by the converter is a function of the firing angle, transformer tap position and number of connected filter, which can be approximated with half of the active power. The losses is a function of the dc voltage and dc current.

The attributes minAlpha and maxAlpha define the range of firing angles for rectifier operation between which no discrete tap changer action takes place. The range is typically 10-18 degrees.

The attributes minGamma and maxGamma define the range of extinction angles for inverter operation between which no discrete tap changer action takes place. The range is typically 17-20 degrees.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|operatingMode (enumeration)
|1..1
|<<CsOperatingModeKind,CsOperatingModeKind>>
|
Indicates whether the DC pole is operating as an inverter or as a rectifier. It is converters control variable used in power flow.


|pPccControl (enumeration)
|1..1
|<<CsPpccControlKind,CsPpccControlKind>>
|
Kind of active power control.


|targetAlpha
|0..1
|<<AngleDegrees,AngleDegrees>>
|
Target firing angle. It is converters control variable used in power flow. It is only applicable for rectifier if continuous tap changer control is used. Allowed values are within the range minAlpha&lt;=targetAlpha&lt;=maxAlpha. The attribute shall be a positive value.


|targetGamma
|0..1
|<<AngleDegrees,AngleDegrees>>
|
Target extinction angle. It is converters control variable used in power flow. It is only applicable for inverter if continuous tap changer control is used. Allowed values are within the range minGamma&lt;=targetGamma&lt;=maxGamma. The attribute shall be a positive value.


|targetIdc
|0..1
|<<CurrentFlow,CurrentFlow>>
|
DC current target value. It is converters control variable used in power flow. The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<ACDCConverter,ACDCConverter>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<ACDCConverter,ACDCConverter>>

|targetPpcc
|0..1
|<<ActivePower,ActivePower>>
|see <<ACDCConverter,ACDCConverter>>

|targetUdc
|0..1
|<<Voltage,Voltage>>
|see <<ACDCConverter,ACDCConverter>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#CurrentLimit]
==== (Description) CurrentLimit

Inheritance path = <<OperationalLimit,OperationalLimit>> => <<IdentifiedObject,IdentifiedObject>>

Operational limit on current.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<CurrentFlow,CurrentFlow>>
|
Limit on current flow. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#DCTerminal]
==== (Description) DCTerminal

Inheritance path = <<DCBaseTerminal,DCBaseTerminal>> => <<ACDCTerminal,ACDCTerminal>> => <<IdentifiedObject,IdentifiedObject>>

An electrical connection point to generic DC conducting equipment.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|connected
|1..1
|<<Boolean,Boolean>>
|see <<ACDCTerminal,ACDCTerminal>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#DisconnectingCircuitBreaker]
==== (Description) DisconnectingCircuitBreaker

Inheritance path = <<Breaker,Breaker>> => <<ProtectedSwitch,ProtectedSwitch>> => <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A circuit breaking device including disconnecting function, eliminating the need for separate disconnectors.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Disconnector]
==== (Description) Disconnector

Inheritance path = <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A manually operated or motor operated mechanical switching device used for changing the connections in a circuit, or for isolating a circuit or equipment from a source of power. It is required to open or close circuits when negligible current is broken or made.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EnergyConsumer]
==== (Description) EnergyConsumer

Inheritance path = <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Generic user of energy - a point of consumption on the power system model.

EnergyConsumer.pfixed, .qfixed, .pfixedPct and .qfixedPct have meaning only if there is no LoadResponseCharacteristic associated with EnergyConsumer or if LoadResponseCharacteristic.exponentModel is set to False.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|p
|1..1
|<<ActivePower,ActivePower>>
|
Active power of the load. Load sign convention is used, i.e. positive sign means flow out from a node.

For voltage dependent loads the value is at rated voltage.

Starting value for a steady state solution.


|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Reactive power of the load. Load sign convention is used, i.e. positive sign means flow out from a node.

For voltage dependent loads the value is at rated voltage.

Starting value for a steady state solution.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EnergySource]
==== (Description) EnergySource

Inheritance path = <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A generic equivalent for an energy supplier on a transmission or distribution voltage level.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|activePower
|1..1
|<<ActivePower,ActivePower>>
|
High voltage source active injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for steady state solutions.


|reactivePower
|1..1
|<<ReactivePower,ReactivePower>>
|
High voltage source reactive injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for steady state solutions.


|voltageAngle
|0..1
|<<AngleRadians,AngleRadians>>
|
Phase angle of a-phase open circuit used when voltage characteristics need to be imposed at the node associated with the terminal of the energy source, such as when voltages and angles from the transmission level are used as input to the distribution network. The attribute shall be a positive value or zero.


|voltageMagnitude
|0..1
|<<Voltage,Voltage>>
|
Phase-to-phase open circuit voltage magnitude used when voltage characteristics need to be imposed at the node associated with the terminal of the energy source, such as when voltages and angles from the transmission level are used as input to the distribution network. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EquivalentInjection]
==== (Description) EquivalentInjection

Inheritance path = <<EquivalentEquipment,EquivalentEquipment>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

This class represents equivalent injections (generation or load). Voltage regulation is allowed only at the point of connection.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|p
|1..1
|<<ActivePower,ActivePower>>
|
Equivalent active power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for steady state solutions.


|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Equivalent reactive power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for steady state solutions.


|regulationStatus
|0..1
|<<Boolean,Boolean>>
|
Specifies the regulation status of the EquivalentInjection. True is regulating. False is not regulating.


|regulationTarget
|0..1
|<<Voltage,Voltage>>
|
The target voltage for voltage regulation. The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ExternalNetworkInjection]
==== (Description) ExternalNetworkInjection

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

This class represents the external network and it is used for IEC 60909 calculations.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|p
|1..1
|<<ActivePower,ActivePower>>
|
Active power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for steady state solutions.


|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Reactive power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for steady state solutions.


|referencePriority
|1..1
|<<Integer,Integer>>
|
Priority of unit for use as powerflow voltage phase angle reference bus selection. 0 = don t care (default) 1 = highest priority. 2 is less than 1 and so on.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Fuse]
==== (Description) Fuse

Inheritance path = <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

An overcurrent protective device with a circuit opening fusible part that is heated and severed by the passage of overcurrent through it. A fuse is considered a switching device because it breaks current.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#GeneratingUnit]
==== (Description) GeneratingUnit

Inheritance path = <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A single or set of synchronous machines for converting mechanical power into alternating-current power. For example, individual machines within a set may be defined for scheduling purposes while a single control signal is derived for the set. In this case there would be a GeneratingUnit for each member of the set and an additional GeneratingUnit corresponding to the set.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|normalPF
|1..1
|<<Float,Float>>
|
Generating unit economic participation factor. The sum of the participation factors across generating units does not have to sum to one. It is used for representing distributed slack participation factor. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#GroundDisconnector]
==== (Description) GroundDisconnector

Inheritance path = <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A manually operated or motor operated mechanical switching device used for isolating a circuit or equipment from ground.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#HydroGeneratingUnit]
==== (Description) HydroGeneratingUnit

Inheritance path = <<GeneratingUnit,GeneratingUnit>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A generating unit whose prime mover is a hydraulic turbine (e.g., Francis, Pelton, Kaplan).



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|normalPF
|1..1
|<<Float,Float>>
|see <<GeneratingUnit,GeneratingUnit>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Jumper]
==== (Description) Jumper

Inheritance path = <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A short section of conductor with negligible impedance which can be manually removed and replaced if the circuit is de-energized. Note that zero-impedance branches can potentially be modelled by other equipment types.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#LinearShuntCompensator]
==== (Description) LinearShuntCompensator

Inheritance path = <<ShuntCompensator,ShuntCompensator>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A linear shunt compensator has banks or sections with equal admittance values.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|sections
|1..1
|<<Float,Float>>
|see <<ShuntCompensator,ShuntCompensator>>

|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#LoadBreakSwitch]
==== (Description) LoadBreakSwitch

Inheritance path = <<ProtectedSwitch,ProtectedSwitch>> => <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A mechanical switching device capable of making, carrying, and breaking currents under normal operating conditions.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#NonConformLoad]
==== (Description) NonConformLoad

Inheritance path = <<EnergyConsumer,EnergyConsumer>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

NonConformLoad represents loads that do not follow a daily load change pattern and whose changes are not correlated with the daily load change pattern.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<EnergyConsumer,EnergyConsumer>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<EnergyConsumer,EnergyConsumer>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#NonlinearShuntCompensator]
==== (Description) NonlinearShuntCompensator

Inheritance path = <<ShuntCompensator,ShuntCompensator>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A non linear shunt compensator has bank or section admittance values that differ. The attributes g, b, g0 and b0 of the associated NonlinearShuntCompensatorPoint describe the total conductance and admittance of a NonlinearShuntCompensatorPoint at a section number specified by NonlinearShuntCompensatorPoint.sectionNumber.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|sections
|1..1
|<<Float,Float>>
|see <<ShuntCompensator,ShuntCompensator>>

|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#NuclearGeneratingUnit]
==== (Description) NuclearGeneratingUnit

Inheritance path = <<GeneratingUnit,GeneratingUnit>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A nuclear generating unit.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|normalPF
|1..1
|<<Float,Float>>
|see <<GeneratingUnit,GeneratingUnit>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PhaseTapChangerAsymmetrical]
==== (Description) PhaseTapChangerAsymmetrical

Inheritance path = <<PhaseTapChangerNonLinear,PhaseTapChangerNonLinear>> => <<PhaseTapChanger,PhaseTapChanger>> => <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Describes the tap model for an asymmetrical phase shifting transformer in which the difference voltage vector adds to the in-phase winding. The out-of-phase winding is the transformer end where the tap changer is located. The angle between the in-phase and out-of-phase windings is named the winding connection angle. The phase shift depends on both the difference voltage magnitude and the winding connection angle.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PhaseTapChangerLinear]
==== (Description) PhaseTapChangerLinear

Inheritance path = <<PhaseTapChanger,PhaseTapChanger>> => <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Describes a tap changer with a linear relation between the tap step and the phase angle difference across the transformer. This is a mathematical model that is an approximation of a real phase tap changer.

The phase angle is computed as stepPhaseShiftIncrement times the tap position.

The voltage magnitude of both sides is the same.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PhaseTapChangerSymmetrical]
==== (Description) PhaseTapChangerSymmetrical

Inheritance path = <<PhaseTapChangerNonLinear,PhaseTapChangerNonLinear>> => <<PhaseTapChanger,PhaseTapChanger>> => <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Describes a symmetrical phase shifting transformer tap model in which the voltage magnitude of both sides is the same. The difference voltage magnitude is the base in an equal-sided triangle where the sides corresponds to the primary and secondary voltages. The phase angle difference corresponds to the top angle and can be expressed as twice the arctangent of half the total difference voltage.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PhaseTapChangerTabular]
==== (Description) PhaseTapChangerTabular

Inheritance path = <<PhaseTapChanger,PhaseTapChanger>> => <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Describes a tap changer with a table defining the relation between the tap step and the phase angle difference across the transformer.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PowerElectronicsConnection]
==== (Description) PowerElectronicsConnection

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A connection to the AC network for energy production or consumption that uses power electronics rather than rotating machines.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|p
|1..1
|<<ActivePower,ActivePower>>
|
Active power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution.


|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Reactive power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RatioTapChanger]
==== (Description) RatioTapChanger

Inheritance path = <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A tap changer that changes the voltage ratio impacting the voltage magnitude but not the phase angle across the transformer.

Angle sign convention (general): Positive value indicates a positive phase shift from the winding where the tap is located to the other winding (for a two-winding transformer).



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RegulatingCondEq]
==== (Description) RegulatingCondEq

Inheritance path = <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A type of conducting equipment that can regulate a quantity (i.e. voltage or flow) at a specific point in the network.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|controlEnabled
|1..1
|<<Boolean,Boolean>>
|
Specifies the regulation status of the equipment. True is regulating, false is not regulating.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RegulatingControl]
==== (Description) RegulatingControl

Inheritance path = <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Specifies a set of equipment that works together to control a power system quantity such as voltage or flow.

Remote bus voltage control is possible by specifying the controlled terminal located at some place remote from the controlling equipment.

The specified terminal shall be associated with the connectivity node of the controlled point. The most specific subtype of RegulatingControl shall be used in case such equipment participate in the control, e.g. TapChangerControl for tap changers.

For flow control, load sign convention is used, i.e. positive sign means flow out from a TopologicalNode (bus) into the conducting equipment.

The attribute minAllowedTargetValue and maxAllowedTargetValue are required in the following cases:

- For a power generating module operated in power factor control mode to specify maximum and minimum power factor values;

- Whenever it is necessary to have an off center target voltage for the tap changer regulator. For instance, due to long cables to off shore wind farms and the need to have a simpler setup at the off shore transformer platform, the voltage is controlled from the land at the connection point for the off shore wind farm. Since there usually is a voltage rise along the cable, there is typical and overvoltage of up 3-4 kV compared to the on shore station. Thus in normal operation the tap changer on the on shore station is operated with a target set point, which is in the lower parts of the dead band.

The attributes minAllowedTargetValue and maxAllowedTargetValue are not related to the attribute targetDeadband and thus they are not treated as an alternative of the targetDeadband. They are needed due to limitations in the local substation controller. The attribute targetDeadband is used to prevent the power flow from move the tap position in circles (hunting) that is to be used regardless of the attributes minAllowedTargetValue and maxAllowedTargetValue.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|discrete
|1..1
|<<Boolean,Boolean>>
|
The regulation is performed in a discrete mode. This applies to equipment with discrete controls, e.g. tap changers and shunt compensators.


|enabled
|1..1
|<<Boolean,Boolean>>
|
The flag tells if regulation is enabled.


|maxAllowedTargetValue
|0..1
|<<Float,Float>>
|
Maximum allowed target value (RegulatingControl.targetValue).


|minAllowedTargetValue
|0..1
|<<Float,Float>>
|
Minimum allowed target value (RegulatingControl.targetValue).


|targetDeadband
|0..1
|<<Float,Float>>
|
This is a deadband used with discrete control to avoid excessive update of controls like tap changers and shunt compensator banks while regulating. The units of those appropriate for the mode. The attribute shall be a positive value or zero. If RegulatingControl.discrete is set to "false", the RegulatingControl.targetDeadband is to be ignored.

Note that for instance, if the targetValue is 100 kV and the targetDeadband is 2 kV the range is from 99 to 101 kV.


|targetValue
|1..1
|<<Float,Float>>
|
The target value specified for case input. This value can be used for the target value without the use of schedules. The value has the units appropriate to the mode attribute.


|targetValueUnitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|
Specify the multiplier for used for the targetValue.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#SolarGeneratingUnit]
==== (Description) SolarGeneratingUnit

Inheritance path = <<GeneratingUnit,GeneratingUnit>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A solar thermal generating unit, connected to the grid by means of a rotating machine. This class does not represent photovoltaic (PV) generation.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|normalPF
|1..1
|<<Float,Float>>
|see <<GeneratingUnit,GeneratingUnit>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#StaticVarCompensator]
==== (Description) StaticVarCompensator

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A facility for providing variable and controllable shunt reactive power. The SVC typically consists of a stepdown transformer, filter, thyristor-controlled reactor, and thyristor-switched capacitor arms.

The SVC may operate in fixed MVar output mode or in voltage control mode. When in voltage control mode, the output of the SVC will be proportional to the deviation of voltage at the controlled bus from the voltage setpoint. The SVC characteristic slope defines the proportion. If the voltage at the controlled bus is equal to the voltage setpoint, the SVC MVar output is zero.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Reactive power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#StationSupply]
==== (Description) StationSupply

Inheritance path = <<EnergyConsumer,EnergyConsumer>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Station supply with load derived from the station output.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<EnergyConsumer,EnergyConsumer>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<EnergyConsumer,EnergyConsumer>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Switch]
==== (Description) Switch

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A generic device designed to close, or open, or both, one or more electric circuits. All switches are two terminal devices including grounding switches. The ACDCTerminal.connected at the two sides of the switch shall not be considered for assessing switch connectivity, i.e. only Switch.open, .normalOpen and .locked are relevant.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|locked
|1..1
|<<Boolean,Boolean>>
|
If true, the switch is locked. The resulting switch state is a combination of locked and Switch.open attributes as follows:

<ul>

<li>locked=true and Switch.open=true. The resulting state is open and locked;</li>

<li>locked=false and Switch.open=true. The resulting state is open;</li>

<li>locked=false and Switch.open=false. The resulting state is closed.</li>

</ul>


|open
|1..1
|<<Boolean,Boolean>>
|
The attribute tells if the switch is considered open when used as input to topology processing.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#SynchronousMachine]
==== (Description) SynchronousMachine

Inheritance path = <<RotatingMachine,RotatingMachine>> => <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

An electromechanical device that operates with shaft rotating synchronously with the network. It is a single machine operating either as a generator or synchronous condenser or pump.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|operatingMode (enumeration)
|1..1
|<<SynchronousMachineOperatingMode,SynchronousMachineOperatingMode>>
|
Current mode of operation.


|referencePriority
|1..1
|<<Integer,Integer>>
|
Priority of unit for use as powerflow voltage phase angle reference bus selection. 0 = don t care (default) 1 = highest priority. 2 is less than 1 and so on.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<RotatingMachine,RotatingMachine>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<RotatingMachine,RotatingMachine>>

|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#TapChangerControl]
==== (Description) TapChangerControl

Inheritance path = <<RegulatingControl,RegulatingControl>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Describes behaviour specific to tap changers, e.g. how the voltage at the end of a line varies with the load level and compensation of the voltage drop by tap adjustment.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|discrete
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingControl,RegulatingControl>>

|enabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingControl,RegulatingControl>>

|maxAllowedTargetValue
|0..1
|<<Float,Float>>
|see <<RegulatingControl,RegulatingControl>>

|minAllowedTargetValue
|0..1
|<<Float,Float>>
|see <<RegulatingControl,RegulatingControl>>

|targetDeadband
|0..1
|<<Float,Float>>
|see <<RegulatingControl,RegulatingControl>>

|targetValue
|1..1
|<<Float,Float>>
|see <<RegulatingControl,RegulatingControl>>

|targetValueUnitMultiplier (enumeration)
|1..1
|<<UnitMultiplier,UnitMultiplier>>
|see <<RegulatingControl,RegulatingControl>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Terminal]
==== (Description) Terminal

Inheritance path = <<ACDCTerminal,ACDCTerminal>> => <<IdentifiedObject,IdentifiedObject>>

An AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|connected
|1..1
|<<Boolean,Boolean>>
|see <<ACDCTerminal,ACDCTerminal>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ThermalGeneratingUnit]
==== (Description) ThermalGeneratingUnit

Inheritance path = <<GeneratingUnit,GeneratingUnit>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A generating unit whose prime mover could be a steam turbine, combustion turbine, or diesel engine.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|normalPF
|1..1
|<<Float,Float>>
|see <<GeneratingUnit,GeneratingUnit>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#VoltageLimit]
==== (Description) VoltageLimit

Inheritance path = <<OperationalLimit,OperationalLimit>> => <<IdentifiedObject,IdentifiedObject>>

Operational limit applied to voltage.

The use of operational VoltageLimit is preferred instead of limits defined at VoltageLevel. The operational VoltageLimits are used, if present.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|value
|1..1
|<<Voltage,Voltage>>
|
Limit on voltage. High or low limit nature of the limit depends upon the properties of the operational limit type. The attribute shall be a positive value or zero.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#VsConverter]
==== (Description) VsConverter

Inheritance path = <<ACDCConverter,ACDCConverter>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

DC side of the voltage source converter (VSC).


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|droop
|0..1
|<<PU,PU>>
|
Droop constant. The pu value is obtained as D [kV/MW] x Sb / Ubdc. The attribute shall be a positive value.


|droopCompensation
|0..1
|<<Resistance,Resistance>>
|
Compensation constant. Used to compensate for voltage drop when controlling voltage at a distant bus. The attribute shall be a positive value.


|pPccControl (enumeration)
|1..1
|<<VsPpccControlKind,VsPpccControlKind>>
|
Kind of control of real power and/or DC voltage.


|qPccControl (enumeration)
|1..1
|<<VsQpccControlKind,VsQpccControlKind>>
|
Kind of reactive power control.


|qShare
|0..1
|<<PerCent,PerCent>>
|
Reactive power sharing factor among parallel converters on Uac control. The attribute shall be a positive value or zero.


|targetPhasePcc
|0..1
|<<AngleDegrees,AngleDegrees>>
|
Phase target at AC side, at point of common coupling. The attribute shall be a positive value.


|targetPowerFactorPcc
|0..1
|<<Float,Float>>
|
Power factor target at the AC side, at point of common coupling. The attribute shall be a positive value.


|targetPWMfactor
|0..1
|<<Float,Float>>
|
Magnitude of pulse-modulation factor. The attribute shall be a positive value.


|targetQpcc
|0..1
|<<ReactivePower,ReactivePower>>
|
Reactive power injection target in AC grid, at point of common coupling. Load sign convention is used, i.e. positive sign means flow out from a node.


|targetUpcc
|0..1
|<<Voltage,Voltage>>
|
Voltage target in AC grid, at point of common coupling. The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|p
|1..1
|<<ActivePower,ActivePower>>
|see <<ACDCConverter,ACDCConverter>>

|q
|1..1
|<<ReactivePower,ReactivePower>>
|see <<ACDCConverter,ACDCConverter>>

|targetPpcc
|0..1
|<<ActivePower,ActivePower>>
|see <<ACDCConverter,ACDCConverter>>

|targetUdc
|0..1
|<<Voltage,Voltage>>
|see <<ACDCConverter,ACDCConverter>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#WindGeneratingUnit]
==== (Description) WindGeneratingUnit

Inheritance path = <<GeneratingUnit,GeneratingUnit>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A wind driven generating unit, connected to the grid by means of a rotating machine. May be used to represent a single turbine or an aggregation.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|normalPF
|1..1
|<<Float,Float>>
|see <<GeneratingUnit,GeneratingUnit>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===


=== Abstract Classes

[#ACDCConverter]
==== ACDCConverter

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A unit with valves for three phases, together with unit control equipment, essential protective and switching devices, DC storage capacitors, phase reactors and auxiliaries, if any, used for conversion.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|p
|1..1
|<<ActivePower,ActivePower>>
|
Active power at the point of common coupling. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution in the case a simplified power flow model is used.


|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Reactive power at the point of common coupling. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution in the case a simplified power flow model is used.


|targetPpcc
|0..1
|<<ActivePower,ActivePower>>
|
Real power injection target in AC grid, at point of common coupling. Load sign convention is used, i.e. positive sign means flow out from a node.


|targetUdc
|0..1
|<<Voltage,Voltage>>
|
Target value for DC voltage magnitude. The attribute shall be a positive value.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ACDCTerminal]
==== ACDCTerminal

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

An electrical connection point (AC or DC) to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|connected
|1..1
|<<Boolean,Boolean>>
|
The connected status is related to a bus-branch model and the topological node to terminal relation. True implies the terminal is connected to the related topological node and false implies it is not.

In a bus-branch model, the connected status is used to tell if equipment is disconnected without having to change the connectivity described by the topological node to terminal relation. A valid case is that conducting equipment can be connected in one end and open in the other. In particular for an AC line segment, where the reactive line charging can be significant, this is a relevant case.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ConductingEquipment]
==== ConductingEquipment

Inheritance path = <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The parts of the AC power system that are designed to carry current or that are conductively connected through terminals.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#DCBaseTerminal]
==== DCBaseTerminal

Inheritance path = <<ACDCTerminal,ACDCTerminal>> => <<IdentifiedObject,IdentifiedObject>>

An electrical connection point at a piece of DC conducting equipment. DC terminals are connected at one physical DC node that may have multiple DC terminals connected. A DC node is similar to an AC connectivity node. The model requires that DC connections are distinct from AC connections.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|connected
|1..1
|<<Boolean,Boolean>>
|see <<ACDCTerminal,ACDCTerminal>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EnergyConnection]
==== EnergyConnection

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A connection of energy generation or consumption on the power system model.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#Equipment]
==== Equipment

Inheritance path = <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The parts of a power system that are physical devices, electronic or mechanical.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|inService
|1..1
|<<Boolean,Boolean>>
|
Specifies the availability of the equipment. True means the equipment is available for topology processing, which determines if the equipment is energized or not. False means that the equipment is treated by network applications as if it is not in the model.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#EquipmentContainer]
==== EquipmentContainer


A modelling construct to provide a root class for containing equipment.



[#EquivalentEquipment]
==== EquivalentEquipment

Inheritance path = <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The class represents equivalent objects that are the result of a network reduction. The class is the base for equivalent objects of different types.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#IdentifiedObject]
==== IdentifiedObject


This is a root class to provide common identification for all classes needing identification and naming attributes.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|mRID
|1..1
|<<String,String>>
|
Master resource identifier issued by a model authority. The mRID is unique within an exchange context. Global uniqueness is easily achieved by using a UUID, as specified in RFC 4122, for the mRID. The use of UUID is strongly recommended.

For CIMXML data files in RDF syntax conforming to IEC 61970-552, the mRID is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.

|===

[#OperationalLimit]
==== OperationalLimit

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

A value and normal value associated with a specific kind of limit.

The sub class value and normalValue attributes vary inversely to the associated OperationalLimitType.acceptableDuration (acceptableDuration for short).

If a particular piece of equipment has multiple operational limits of the same kind (apparent power, current, etc.), the limit with the greatest acceptableDuration shall have the smallest limit value and the limit with the smallest acceptableDuration shall have the largest limit value. Note: A large current can only be allowed to flow through a piece of equipment for a short duration without causing damage, but a lesser current can be allowed to flow for a longer duration.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PhaseTapChanger]
==== PhaseTapChanger

Inheritance path = <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A transformer phase shifting tap model that controls the phase angle difference across the power transformer and potentially the active power flow through the power transformer. This phase tap model may also impact the voltage magnitude.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PhaseTapChangerNonLinear]
==== PhaseTapChangerNonLinear

Inheritance path = <<PhaseTapChanger,PhaseTapChanger>> => <<TapChanger,TapChanger>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

The non-linear phase tap changer describes the non-linear behaviour of a phase tap changer. This is a base class for the symmetrical and asymmetrical phase tap changer models. The details of these models can be found in IEC 61970-301.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<TapChanger,TapChanger>>

|step
|1..1
|<<Float,Float>>
|see <<TapChanger,TapChanger>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PowerElectronicsUnit]
==== PowerElectronicsUnit

Inheritance path = <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A generating unit or battery or aggregation that connects to the AC network using power electronics rather than rotating machines.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#PowerSystemResource]
==== PowerSystemResource

Inheritance path = <<IdentifiedObject,IdentifiedObject>>

A power system resource (PSR) can be an item of equipment such as a switch, an equipment container containing many individual items of equipment such as a substation, or an organisational entity such as sub-control area. Power system resources can have measurements associated.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ProtectedSwitch]
==== ProtectedSwitch

Inheritance path = <<Switch,Switch>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A ProtectedSwitch is a switching device that can be operated by ProtectionEquipment.



*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|locked
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|open
|1..1
|<<Boolean,Boolean>>
|see <<Switch,Switch>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#RotatingMachine]
==== RotatingMachine

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A rotating machine which may be used as a generator or motor.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|p
|1..1
|<<ActivePower,ActivePower>>
|
Active power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution.


|q
|1..1
|<<ReactivePower,ReactivePower>>
|
Reactive power injection. Load sign convention is used, i.e. positive sign means flow out from a node.

Starting value for a steady state solution.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#ShuntCompensator]
==== ShuntCompensator

Inheritance path = <<RegulatingCondEq,RegulatingCondEq>> => <<EnergyConnection,EnergyConnection>> => <<ConductingEquipment,ConductingEquipment>> => <<Equipment,Equipment>> => <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

A shunt capacitor or reactor or switchable bank of shunt capacitors or reactors. A section of a shunt compensator is an individual capacitor or reactor. A negative value for bPerSection indicates that the compensator is a reactor. ShuntCompensator is a single terminal device. Ground is implied.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|sections
|1..1
|<<Float,Float>>
|
Shunt compensator sections in use. Starting value for steady state solution. The attribute shall be a positive value or zero. Non integer values are allowed to support continuous variables. The reasons for continuous value are to support study cases where no discrete shunt compensators has yet been designed, a solutions where a narrow voltage band force the sections to oscillate or accommodate for a continuous solution as input.

For LinearShuntConpensator the value shall be between zero and ShuntCompensator.maximumSections. At value zero the shunt compensator conductance and admittance is zero. Linear interpolation of conductance and admittance between the previous and next integer section is applied in case of non-integer values.

For NonlinearShuntCompensator-s shall only be set to one of the NonlinearShuntCompenstorPoint.sectionNumber. There is no interpolation between NonlinearShuntCompenstorPoint-s.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|controlEnabled
|1..1
|<<Boolean,Boolean>>
|see <<RegulatingCondEq,RegulatingCondEq>>

|inService
|1..1
|<<Boolean,Boolean>>
|see <<Equipment,Equipment>>

|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===

[#TapChanger]
==== TapChanger

Inheritance path = <<PowerSystemResource,PowerSystemResource>> => <<IdentifiedObject,IdentifiedObject>>

Mechanism for changing transformer winding tap positions.


*Native Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description

|controlEnabled
|1..1
|<<Boolean,Boolean>>
|
Specifies the regulation status of the equipment. True is regulating, false is not regulating.


|step
|1..1
|<<Float,Float>>
|
Tap changer position.

Starting step for a steady state solution. Non integer values are allowed to support continuous tap variables. The reasons for continuous value are to support study cases where no discrete tap changer has yet been designed, a solution where a narrow voltage band forces the tap step to oscillate or to accommodate for a continuous solution as input.

The attribute shall be equal to or greater than lowStep and equal to or less than highStep.

|===

*Inherited Members*

[%header,width="100%",cols="25%,^10%,20%,45%"]
|===
|name |mult |type |description


|mRID
|1..1
|<<String,String>>
|see <<IdentifiedObject,IdentifiedObject>>
|===



=== Enumerations

[#AsynchronousMachineKind]
==== AsynchronousMachineKind

Kind of Asynchronous Machine.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|generator
|
The Asynchronous Machine is a generator.


|motor
|
The Asynchronous Machine is a motor.

|===
[#BatteryStateKind]
==== BatteryStateKind

The state of the battery unit.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|charging
|
Stored energy is increasing.


|discharging
|
Stored energy is decreasing.


|empty
|
Unable to discharge, and not charging.


|full
|
Unable to charge, and not discharging.


|waiting
|
Neither charging nor discharging, but able to do so.

|===
[#CsOperatingModeKind]
==== CsOperatingModeKind

Operating mode for HVDC line operating as Current Source Converter.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|inverter
|
Operating as inverter, which is the power receiving end.


|rectifier
|
Operating as rectifier, which is the power sending end.

|===
[#CsPpccControlKind]
==== CsPpccControlKind

Active power control modes for HVDC line operating as Current Source Converter.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|activePower
|
Control is active power control at AC side, at point of common coupling. Target is provided by ACDCConverter.targetPpcc.


|dcCurrent
|
Control is DC current with target value provided by CsConverter.targetIdc.


|dcVoltage
|
Control is DC voltage with target value provided by ACDCConverter.targetUdc.

|===
[#SynchronousMachineOperatingMode]
==== SynchronousMachineOperatingMode

Synchronous machine operating mode.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|condenser
|
Operating as condenser.


|generator
|
Operating as generator.


|motor
|
Operating as motor.

|===
[#UnitMultiplier]
==== UnitMultiplier

The unit multipliers defined for the CIM. When applied to unit symbols, the unit symbol is treated as a derived unit. Regardless of the contents of the unit symbol text, the unit symbol shall be treated as if it were a single-character unit symbol. Unit symbols should not contain multipliers, and it should be left to the multiplier to define the multiple for an entire data type.

For example, if a unit symbol is "m2Pers" and the multiplier is "k", then the value is k(m**2/s), and the multiplier applies to the entire final value, not to any individual part of the value. This can be conceptualized by substituting a derived unit symbol for the unit type. If one imagines that the symbol "" represents the derived unit "m2Pers", then applying the multiplier "k" can be conceptualized simply as "k".

For example, the SI unit for mass is "kg" and not "g". If the unit symbol is defined as "kg", then the multiplier is applied to "kg" as a whole and does not replace the "k" in front of the "g". In this case, the multiplier of "m" would be used with the unit symbol of "kg" to represent one gram. As a text string, this violates the instructions in IEC 80000-1. However, because the unit symbol in CIM is treated as a derived unit instead of as an SI unit, it makes more sense to conceptualize the "kg" as if it were replaced by one of the proposed replacements for the SI mass symbol. If one imagines that the "kg" were replaced by a symbol "", then it is easier to conceptualize the multiplier "m" as creating the proper unit "m", and not the forbidden unit "mkg".


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|E
|
Exa 10**18.


|G
|
Giga 10**9.


|M
|
Mega 10**6.


|P
|
Peta 10**15.


|T
|
Tera 10**12.


|Y
|
Yotta 10**24.


|Z
|
Zetta 10**21.


|a
|
Atto 10**-18.


|c
|
Centi 10**-2.


|d
|
Deci 10**-1.


|da
|
Deca 10**1.


|f
|
Femto 10**-15.


|h
|
Hecto 10**2.


|k
|
Kilo 10**3.


|m
|
Milli 10**-3.


|micro
|
Micro 10**-6.


|n
|
Nano 10**-9.


|none
|
No multiplier or equivalently multiply by 1.


|p
|
Pico 10**-12.


|y
|
Yocto 10**-24.


|z
|
Zepto 10**-21.

|===
[#UnitSymbol]
==== UnitSymbol

The derived units defined for usage in the CIM. In some cases, the derived unit is equal to an SI unit. Whenever possible, the standard derived symbol is used instead of the formula for the derived unit. For example, the unit symbol Farad is defined as "F" instead of "CPerV". In cases where a standard symbol does not exist for a derived unit, the formula for the unit is used as the unit symbol. For example, density does not have a standard symbol and so it is represented as "kgPerm3". With the exception of the "kg", which is an SI unit, the unit symbols do not contain multipliers and therefore represent the base derived unit to which a multiplier can be applied as a whole.

Every unit symbol is treated as an unparseable text as if it were a single-letter symbol. The meaning of each unit symbol is defined by the accompanying descriptive text and not by the text contents of the unit symbol.

To allow the widest possible range of serializations without requiring special character handling, several substitutions are made which deviate from the format described in IEC 80000-1. The division symbol "/" is replaced by the letters "Per". Exponents are written in plain text after the unit as "m3" instead of being formatted as "m" with a superscript of 3 or introducing a symbol as in "m^3". The degree symbol "" is replaced with the letters "deg". Any clarification of the meaning for a substitution is included in the description for the unit symbol.

Non-SI units are included in list of unit symbols to allow sources of data to be correctly labelled with their non-SI units (for example, a GPS sensor that is reporting numbers that represent feet instead of meters). This allows software to use the unit symbol information correctly convert and scale the raw data of those sources into SI-based units.

The integer values are used for harmonization with IEC 61850.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|A
|
Current in amperes.


|A2
|
Amperes squared (A).


|A2h
|
Ampere-squared hour, ampere-squared hour.


|A2s
|
Ampere squared time in square amperes (As).


|APerA
|
Current, ratio of amperages. Note: Users may need to supply a prefix such as m to show rates such as mA/A.


|APerm
|
A/m, magnetic field strength, amperes per metre.


|Ah
|
Ampere-hours, ampere-hours.


|As
|
Ampere seconds (As).


|Bq
|
Radioactivity in becquerels (1/s).


|Btu
|
Energy, British Thermal Units.


|C
|
Electric charge in coulombs (As).


|CPerkg
|
Exposure (x rays), coulombs per kilogram.


|CPerm2
|
Surface charge density, coulombs per square metre.


|CPerm3
|
Electric charge density, coulombs per cubic metre.


|F
|
Electric capacitance in farads (C/V).


|FPerm
|
Permittivity, farads per metre.


|G
|
Magnetic flux density, gausses (1 G = 10-4 T).


|Gy
|
Absorbed dose in grays (J/kg).


|GyPers
|
Absorbed dose rate, grays per second.


|H
|
Electric inductance in henrys (Wb/A).


|HPerm
|
Permeability, henrys per metre.


|Hz
|
Frequency in hertz (1/s).


|HzPerHz
|
Frequency, rate of frequency change. Note: Users may need to supply a prefix such as m to show rates such as mHz/Hz.


|HzPers
|
Rate of change of frequency in hertz per second.


|J
|
Energy in joules (Nm = CV = Ws).


|JPerK
|
Heat capacity in joules/kelvin.


|JPerkg
|
Specific energy, Joules / kg.


|JPerkgK
|
Specific heat capacity, specific entropy, joules per kilogram Kelvin.


|JPerm2
|
Insulation energy density, joules per square metre or watt second per square metre.


|JPerm3
|
Energy density, joules per cubic metre.


|JPermol
|
Molar energy, joules per mole.


|JPermolK
|
Molar entropy, molar heat capacity, joules per mole kelvin.


|JPers
|
Energy rate in joules per second (J/s).


|K
|
Temperature in kelvins.


|KPers
|
Temperature change rate in kelvins per second.


|M
|
Length, nautical miles (1 M = 1852 m).


|Mx
|
Magnetic flux, maxwells (1 Mx = 10-8 Wb).


|N
|
Force in newtons (kgm/s).


|NPerm
|
Surface tension, newton per metre.


|Nm
|
Moment of force, newton metres.


|Oe
|
Magnetic field in oersteds, (1 Oe = (103/4p) A/m).


|Pa
|
Pressure in pascals (N/m). Note: the absolute or relative measurement of pressure is implied with this entry. See below for more explicit forms.


|PaPers
|
Pressure change rate in pascals per second.


|Pas
|
Dynamic viscosity, pascal seconds.


|Q
|
Quantity power, Q.


|Qh
|
Quantity energy, Qh.


|S
|
Conductance in siemens.


|SPerm
|
Conductance per length (F/m).


|Sv
|
Dose equivalent in sieverts (J/kg).


|T
|
Magnetic flux density in teslas (Wb/m2).


|V
|
Electric potential in volts (W/A).


|V2
|
Volt squared (W/A).


|V2h
|
Volt-squared hour, volt-squared-hours.


|VA
|
Apparent power in volt amperes. See also real power and reactive power.


|VAh
|
Apparent energy in volt ampere hours.


|VAr
|
Reactive power in volt amperes reactive. The reactive or imaginary component of electrical power (VIsin(phi)). (See also real power and apparent power).

Note: Different meter designs use different methods to arrive at their results. Some meters may compute reactive power as an arithmetic value, while others compute the value vectorially. The data consumer should determine the method in use and the suitability of the measurement for the intended purpose.


|VArh
|
Reactive energy in volt ampere reactive hours.


|VPerHz
|
Magnetic flux in volt per hertz.


|VPerV
|
Voltage, ratio of voltages. Note: Users may need to supply a prefix such as m to show rates such as mV/V.


|VPerVA
|
Power factor, PF, the ratio of the active power to the apparent power. Note: The sign convention used for power factor will differ between IEC meters and EEI (ANSI) meters. It is assumed that the data consumers understand the type of meter being used and agree on the sign convention in use at any given utility.


|VPerVAr
|
Power factor, PF, the ratio of the active power to the apparent power. Note: The sign convention used for power factor will differ between IEC meters and EEI (ANSI) meters. It is assumed that the data consumers understand the type of meter being used and agree on the sign convention in use at any given utility.


|VPerm
|
Electric field strength, volts per metre.


|Vh
|
Volt-hour, Volt hours.


|Vs
|
Volt seconds (Ws/A).


|W
|
Real power in watts (J/s). Electrical power may have real and reactive components. The real portion of electrical power (I&#178;R or VIcos(phi)), is expressed in Watts. See also apparent power and reactive power.


|WPerA
|
Active power per current flow, watts per Ampere.


|WPerW
|
Signal Strength, ratio of power. Note: Users may need to supply a prefix such as m to show rates such as mW/W.


|WPerm2
|
Heat flux density, irradiance, watts per square metre.


|WPerm2sr
|
Radiance, watts per square metre steradian.


|WPermK
|
Thermal conductivity in watt/metres kelvin.


|WPers
|
Ramp rate in watts per second.


|WPersr
|
Radiant intensity, watts per steradian.


|Wb
|
Magnetic flux in webers (Vs).


|Wh
|
Real energy in watt hours.


|anglemin
|
Plane angle, minutes.


|anglesec
|
Plane angle, seconds.


|bar
|
Pressure in bars, (1 bar = 100 kPa).


|cd
|
Luminous intensity in candelas.


|charPers
|
Data rate (baud) in characters per second.


|character
|
Number of characters.


|cosPhi
|
Power factor, dimensionless.

Note 1: This definition of power factor only holds for balanced systems. See the alternative definition under code 153.

Note 2: Beware of differing sign conventions in use between the IEC and EEI. It is assumed that the data consumer understands the type of meter in use and the sign convention in use by the utility.


|count
|
Amount of substance, Counter value.


|d
|
Time in days, day = 24 h = 86400 s.


|dB
|
Sound pressure level in decibels. Note: multiplier d is included in this unit symbol for compatibility with IEC 61850-7-3.


|dBm
|
Power level (logarithmic ratio of signal strength , Bel-mW), normalized to 1mW. Note: multiplier d is included in this unit symbol for compatibility with IEC 61850-7-3.


|deg
|
Plane angle in degrees.


|degC
|
Relative temperature in degrees Celsius.

In the SI unit system the symbol is C. Electric charge is measured in coulomb that has the unit symbol C. To distinguish degree Celsius from coulomb the symbol used in the UML is degC. The reason for not using C is that the special character is difficult to manage in software.


|ft3
|
Volume, cubic feet.


|gPerg
|
Concentration, The ratio of the mass of a solute divided by the mass of the solution. Note: Users may need use a prefix such a to express a quantity such as g/g.


|gal
|
Volume in gallons, US gallon (1 gal = 231 in3 = 128 fl ounce).


|h
|
Time in hours, hour = 60 min = 3600 s.


|ha
|
Area, hectares.


|kat
|
Catalytic activity, katal = mol / s.


|katPerm3
|
Catalytic activity concentration, katals per cubic metre.


|kg
|
Mass in kilograms. Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgPerJ
|
Weight per energy in kilograms per joule (kg/J). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgPerm3
|
Density in kilogram/cubic metres (kg/m). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgm
|
Moment of mass in kilogram metres (kgm) (first moment of mass). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kgm2
|
Moment of mass in kilogram square metres (kgm) (Second moment of mass, commonly called the moment of inertia). Note: multiplier k is included in this unit symbol for compatibility with IEC 61850-7-3.


|kn
|
Speed, knots (1 kn = 1852/3600) m/s.


|l
|
Volume in litres, litre = dm3 = m3/1000.


|lPerh
|
Volumetric flow rate, litres per hour.


|lPerl
|
Concentration, The ratio of the volume of a solute divided by the volume of the solution. Note: Users may need use a prefix such a to express a quantity such as L/L.


|lPers
|
Volumetric flow rate in litres per second.


|lm
|
Luminous flux in lumens (cdsr).


|lx
|
Illuminance in lux (lm/m).


|m
|
Length in metres.


|m2
|
Area in square metres (m).


|m2Pers
|
Viscosity in square metres / second (m/s).


|m3
|
Volume in cubic metres (m).


|m3Compensated
|
Volume, cubic metres, with the value compensated for weather effects.


|m3Perh
|
Volumetric flow rate, cubic metres per hour.


|m3Perkg
|
Specific volume, cubic metres per kilogram, v.


|m3Pers
|
Volumetric flow rate in cubic metres per second (m/s).


|m3Uncompensated
|
Volume, cubic metres, with the value uncompensated for weather effects.


|mPerm3
|
Fuel efficiency in metres per cubic metres (m/m).


|mPers
|
Velocity in metres per second (m/s).


|mPers2
|
Acceleration in metres per second squared (m/s).


|min
|
Time in minutes, minute = 60 s.


|mmHg
|
Pressure, millimetres of mercury (1 mmHg is approximately 133.3 Pa).


|mol
|
Amount of substance in moles.


|molPerkg
|
Concentration, Molality, the amount of solute in moles and the amount of solvent in kilograms.


|molPerm3
|
Concentration, The amount of substance concentration, (c), the amount of solvent in moles divided by the volume of solution in m.


|molPermol
|
Concentration, Molar fraction, the ratio of the molar amount of a solute divided by the molar amount of the solution.


|none
|
Dimension less quantity, e.g. count, per unit, etc.


|ohm
|
Electric resistance in ohms (V/A).


|ohmPerm
|
Electric resistance per length in ohms per metre ((V/A)/m).


|ohmm
|
Resistivity, ohm metres, (rho).


|onePerHz
|
Reciprocal of frequency (1/Hz).


|onePerm
|
Wavenumber, reciprocal metres, (1/m).


|ppm
|
Concentration in parts per million.


|rad
|
Plane angle in radians (m/m).


|radPers
|
Angular velocity in radians per second (rad/s).


|radPers2
|
Angular acceleration, radians per second squared.


|rev
|
Amount of rotation, revolutions.


|rotPers
|
Rotations per second (1/s). See also Hz (1/s).


|s
|
Time in seconds.


|sPers
|
Time, Ratio of time. Note: Users may need to supply a prefix such as &#181; to show rates such as &#181;s/s.


|sr
|
Solid angle in steradians (m2/m2).


|therm
|
Energy, therms.


|tonne
|
Mass in tons, tonne or metric ton (1000 kg = 1 Mg).

|===
[#VsPpccControlKind]
==== VsPpccControlKind

Types applicable to the control of real power and/or DC voltage by voltage source converter.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|pPcc
|
Control is real power at point of common coupling. The target value is provided by ACDCConverter.targetPpcc.


|pPccAndUdcDroop
|
Control is active power at point of common coupling and local DC voltage, with the droop. Target values are provided by ACDCConverter.targetPpcc, ACDCConverter.targetUdc and VsConverter.droop.


|pPccAndUdcDroopPilot
|
Control is active power at point of common coupling and the pilot DC voltage, with the droop. The mode is used for Multi Terminal High Voltage DC (MTDC) systems where multiple HVDC Substations are connected to the HVDC transmission lines. The pilot voltage is then used to coordinate the control the DC voltage across the HVDC substations. Targets are provided by ACDCConverter.targetPpcc, ACDCConverter.targetUdc and VsConverter.droop.


|pPccAndUdcDroopWithCompensation
|
Control is active power at point of common coupling and compensated DC voltage, with the droop. Compensation factor is the resistance, as an approximation of the DC voltage of a common (real or virtual) node in the DC network. Targets are provided by ACDCConverter.targetPpcc, ACDCConverter.targetUdc, VsConverter.droop and VsConverter.droopCompensation.


|phasePcc
|
Control is phase at point of common coupling. Target is provided by VsConverter.targetPhasePcc.


|udc
|
Control is DC voltage with target value provided by ACDCConverter.targetUdc.

|===
[#VsQpccControlKind]
==== VsQpccControlKind

Kind of reactive power control at point of common coupling for a voltage source converter.


[%header,width="100%",cols="25%,75%"]
|===
|name |description

|powerFactorPcc
|
Control is power factor at point of common coupling. Target is provided by VsConverter.targetPowerFactorPcc.


|pulseWidthModulation
|
No explicit control. Pulse-modulation factor is directly set in magnitude (VsConverter.targetPWMfactor) and phase (VsConverter.targetPhasePcc).


|reactivePcc
|
Control is reactive power at point of common coupling. Target is provided by VsConverter.targetQpcc.


|voltagePcc
|
Control is voltage at point of common coupling. Target is provided by VsConverter.targetUpcc.

|===

=== Datatypes

[#ActivePower]
==== ActivePower

Product of RMS value of the voltage and the RMS value of the in-phase component of the current.


XSD type: float

[#AngleDegrees]
==== AngleDegrees

Measurement of angle in degrees.


XSD type: float

[#AngleRadians]
==== AngleRadians

Phase angle in radians.


XSD type: float

[#ApparentPower]
==== ApparentPower

Product of the RMS value of the voltage and the RMS value of the current.


XSD type: float

[#CurrentFlow]
==== CurrentFlow

Electrical current with sign convention: positive flow is out of the conducting equipment into the connectivity node. Can be both AC and DC.


XSD type: float

[#PU]
==== PU

Per Unit - a positive or negative value referred to a defined base. Values typically range from -10 to +10.


XSD type: float

[#PerCent]
==== PerCent

Percentage on a defined base. For example, specify as 100 to indicate at the defined base.


XSD type: float

[#ReactivePower]
==== ReactivePower

Product of RMS value of the voltage and the RMS value of the quadrature component of the current.


XSD type: float

[#RealEnergy]
==== RealEnergy

Real electrical energy.


XSD type: float

[#Resistance]
==== Resistance

Resistance (real part of impedance).


XSD type: float

[#Voltage]
==== Voltage

Electrical voltage, can be both AC and DC.


XSD type: float


=== Primitive Types

[#CPSM-NA-SteadyStateHypothesis-Boolean]
==== Boolean

A type with the value space "true" and "false".


XSD type: boolean

[#CPSM-NA-SteadyStateHypothesis-Float]
==== Float

A floating point number. The range is unspecified and not limited.


XSD type: float

[#CPSM-NA-SteadyStateHypothesis-Integer]
==== Integer

An integer number. The range is unspecified and not limited.


XSD type: integer

[#CPSM-NA-SteadyStateHypothesis-String]
==== String

A string consisting of a sequence of characters. The character encoding is UTF-8. The string length is unspecified and unlimited.


XSD type: string

